### ISSUE TITLE
Additional datastore metrics

### ISSUE THREAD

**Issue by ghost** [Oxalide/vsphere-influxdb-go#15]
Hi,

Any plans to support additional datastore metrics (e.g. used space, capacity)? It looks like the 'Datastore' object type is not currently supported.

Thanks,
Steve

**Comment by sofixa** [comment]
Yep, it isn't really supported, but there's an Issue for that #7 . I'm not sure VMware support usage, capacity in the Performance Manager API, so it might be a bit complicated. If you're willing to give it a Go (no pun intended), you're more than welcome to try :)

**Comment by sofixa** [comment]
#29 has been merged which should add the metrics you asked for.
