### ISSUE TITLE
vSAN Stats

### ISSUE THREAD

**Issue by eschek87** [Oxalide/vsphere-influxdb-go#23]
Hi,
it is possible to query vSAN stats as described here:
https://github.com/lamw/mapping-vsan-perf-stats-to-powercli-api/blob/master/README.md#

Best Regards,
Stephan

**Comment by sofixa** [comment]
Hi, 

It should be possible. Do you want to give it a try?

Cheers,
Adrian

**Comment by eschek87** [comment]
Hello,

yes for sure.

Regards,
Stephan

**Comment by eschek87** [comment]
any news on this?

**Comment by sofixa** [comment]
Not on my part, vSAN metrics are in a [completely different object vSAN Performance Manager](http://pubs.vmware.com/vsphere-6-5/index.jsp?topic=%2Fcom.vmware.vsan.apiref.doc%2Fvim.cluster.VsanPerformanceManager.html), so it'd require some coding, and i don't have access to a vSAN environment so i won't be able to test.

**Comment by DRDAVIDBANNER** [comment]
I have a developement vsan environment I could allow you some limited access to if you need to test?

**Comment by eschek87** [comment]
Yeah this would be cool.
