### ISSUE TITLE
Adding VirtualMachine disk.used.latest metric?

### ISSUE THREAD

**Issue by MrDibbley** [Oxalide/vsphere-influxdb-go#24]
Is it possible to add additional metric to the json? i have tried to add virtualMachine,disk.used.latest liek this 

`                        "ObjectType": [ "VirtualMachine" ],
                        "Definition": [
                        { "Metric": "datastore.datastoreVMObservedLatency.latest", "Instances": "*" },
                        { "Metric": "disk.used.latest", "Instances": "*" }
                        ]
`

but no metrics are available in the influxdb that i can see looking in disk and virtual machine? 

or is it not yet possible to add additional custom metric yet?

**Comment by sofixa** [comment]
Hi,

You can only add metrics that are available through the VMware Performance Manager, and you can find a full list here - http://www.virten.net/2015/05/vsphere-6-0-performance-counter-description/.

**Comment by MrDibbley** [comment]
in the example above, it is shown on the page you linked, :

disk.used.latest	Space actually used	KB	Amount of space actually used by the virtual machine or the datastore

yet returns no data :(
