### ISSUE TITLE
data cannot be selected in grafana from Influxdb

### ISSUE THREAD

**Issue by jm0477** [Oxalide/vsphere-influxdb-go#26]
Data is collected and imported into Influxdb, but I cannot select it from grafana:

2017/06/17 10:51:40 21105
2017/06/17 10:51:40 50352
2017/06/17 10:51:40 56760
2017/06/17 10:51:40 40104
2017/06/17 10:51:40 767119
2017/06/17 10:51:40 496272
2017/06/17 10:51:40 1241
2017/06/17 10:51:40 6303
2017/06/17 10:51:40 84942
2017/06/17 10:51:40 60156
2017/06/17 10:51:40 59753
2017/06/17 10:51:40 34325
2017/06/17 10:51:40 sent data to Influxdb

**Comment by sofixa** [comment]
@jm0477 What do you mean you can't select it in Grafana? Have you tried checking in InfluxDB if everything is there(show measurements, for instance) ?
