### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by acobaugh** [Oxalide/vsphere-influxdb-go#34]
After upgrading from e62722a0796ecfd47684ce38c191308c13558d6c to 33dc0476fd679a8ce431da8f49bd3d371b3d07fc, we noticed our run times with 3 vcenters ~5k VMs went from ~30s per run to ~2m+, sometimes taking as long as 5 minutes to complete.

Git bisect wasn't very helpful as a lot of the steps wouldn't build for one reason or another. Poking around in the code, if I comment out https://github.com/Oxalide/vsphere-influxdb-go/blob/master/vsphere-influxdb.go#L635, our runs are now back to around 30s. I'm not familiar enough with the structure of this code, but I wonder if that whole block shouldn't even be there, since it looks like we're also retrieving all resource pools further up at https://github.com/Oxalide/vsphere-influxdb-go/blob/master/vsphere-influxdb.go#L331?

**Comment by sofixa** [comment]
Ping @heldri

**Comment by sofixa** [comment]
Could you try the [latest version, 0.8.1](https://github.com/Oxalide/vsphere-influxdb-go/releases/tag/v0.8.1)  ? I removed the unnecessary second resource pool retrieve, so it should be faster now :)

**Comment by acobaugh** [comment]
Tried with v0.8.2, and my run time for 3 vcenters with a few thousand VMs is now <20s.

**Comment by sofixa** [comment]
Cool, glad it's better :)
