### ISSUE TITLE
Automatically Deleted aged data

### ISSUE THREAD

**Issue by exbane** [Oxalide/vsphere-influxdb-go#37]
@sofixa Good afternoon! It's been a long time. 

I'm testing out the new version of the script and it seems to be working great for me.. I have a question though.. Is there an easy way to have VMs/Hosts/Clusters/Datastores that are no longer in vCenter? For example we just went through a large Storage migration and the old datastores are still showing up in my templates values for the Dashboards in Grafana.. Is there some sort of continuous query that anybody knows of that can delete objects that haven't reported any measurements/fields after so many days/weeks? 

Thanks! 

Adam

**Comment by exbane** [comment]
I have a 90 day retention policy for my vCenter database but it would be nice if certain data was deleted earlier than that for systems that no longer exist..

**Comment by sofixa** [comment]
Hi, @exbane . Long time no see! How have you been? 


I don't think that's possible with CQs, but i think it'd be doable with a script that basically does the following(pseudocode, it can be done with bash, Python, etc.):
```
# get last value per host from the last week
values = `select last(timestamp),"name" from hostsystem where time < now() - 1w group by tag(name) order by desc `
# loop over results
for val in values:
# if the timestamp is too old (last value is from too long ago, e.g. no new data has arrived for that in some time), drop corresponding series
  if val['timestamp'] - now() > too_much:
    DROP series from hostsystem where "name" =~ /val['name']/
```

I've been meaning to implement something similar at work for some time(the retention policy is at 1y, so a cleanup of decommissioned hosts now and then certainly won't hurt...), i'll add it to this repository when i finally get around to doing it :)

Cheers,
Adrian
