### ISSUE TITLE
Error When Running

### ISSUE THREAD

**Issue by egru** [Oxalide/vsphere-influxdb-go#38]
I'm getting the following error when I run this for the first time:

grafana@grafana:~/go/bin$ ./vsphere-influxdb-go
2017/10/14 20:30:46 Starting : vsphere-influxdb-go
2017/10/14 20:30:46 connecting to vcenter: vcenter
2017/10/14 20:30:46 Successfully connected to Influx
2017/10/14 20:30:46 Querying vcenter
2017/10/14 20:30:46 Setting up query inventory of vcenter:  vcenter
2017/10/14 20:30:46 connecting to vcenter: vcenter
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x91676c]

goroutine 1 [running]:
github.com/vmware/govmomi/property.(*Collector).Retrieve(0xc4202060b0, 0x10270a0, 0xc420415d00, 0x106e940, 0x0, 0x0, 0xc4202bdcb0, 0x1, 0x1, 0x9b26a0, ...)
        /home/grafana/go/src/github.com/vmware/govmomi/property/collector.go:157 +0x50c
main.(*VCenter).Query(0xc42020bad0, 0xc4200bc940, 0x1, 0x4, 0xc4200ca180, 0x2, 0x4, 0x3c, 0x0, 0x0, ...)
        /home/grafana/go/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:284 +0x2866
main.queryVCenter(0xc4200bc9c0, 0x13, 0xc4200bc9a0, 0x1d, 0xc420011480, 0xa, 0xc420430e10, 0x2, 0x2, 0xc4200bc940, ...)
        /home/grafana/go/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:738 +0x126
main.main()
        /home/grafana/go/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:808 +0x907

Running against vcenter 6.5

**Comment by sofixa** [comment]
Hi, @egru . 

What is your json conf like?

**Comment by egru** [comment]
I'm using the sample one.

{"Domain": "",
        "Interval": 60,
        "VCenters": [
                { "Username": "user", "Password": "password", "Hostname": "vcenter" }
        ],
	"InfluxDB": {
		"Hostname": "http://influxdb-01.dc-01.lab:8086",
		"Username": "vm",
		"Password": "vmware334",
		"Database": "vmware_performance"
	},
	"Metrics": [
		{ 
			"ObjectType": [ "VirtualMachine", "HostSystem" ], 
			"Definition": [
				{ "Metric": "cpu.usage.average", "Instances": "*" },
				{ "Metric": "cpu.usage.maximum", "Instances": "*" },
				{ "Metric": "cpu.usagemhz.average", "Instances": "*" },
				{ "Metric": "cpu.usagemhz.maximum", "Instances": "*" },
				{ "Metric": "cpu.wait.summation", "Instances": "*" },
				{ "Metric": "cpu.system.summation", "Instances": "*" },
				{ "Metric": "cpu.ready.summation", "Instances": "*" },
				{ "Metric": "mem.usage.average", "Instances": "*" },
				{ "Metric": "mem.usage.maximum", "Instances": "*" },
				{ "Metric": "mem.consumed.average", "Instances": "*" },
				{ "Metric": "mem.consumed.maximum", "Instances": "*" },
				{ "Metric": "mem.active.average", "Instances": "*" },
				{ "Metric": "mem.active.maximum", "Instances": "*" },
				{ "Metric": "mem.vmmemctl.average", "Instances": "*" },
				{ "Metric": "mem.vmmemctl.maximum", "Instances": "*" },
				{ "Metric": "mem.totalCapacity.average", "Instances": "*" },
				{ "Metric": "net.packetsRx.summation", "Instances": "*" },
			        { "Metric": "net.packetsTx.summation", "Instances": "*" },
				{ "Metric": "net.throughput.usage.average", "Instances": "*" },
				{ "Metric": "net.received.average", "Instances": "*" },
				{ "Metric": "net.transmitted.average", "Instances": "*" },
				{ "Metric": "net.throughput.usage.nfs.average", "Instances": "*" },
				{ "Metric": "datastore.numberReadAveraged.average", "Instances": "*" },
				{ "Metric": "datastore.numberWriteAveraged.average", "Instances": "*" },
				{ "Metric": "datastore.read.average", "Instances": "*" },
				{ "Metric": "datastore.write.average", "Instances": "*" },
				{ "Metric": "datastore.totalReadLatency.average", "Instances": "*" },
				{ "Metric": "datastore.totalWriteLatency.average", "Instances": "*" },
				{ "Metric": "mem.capacity.provisioned.average", "Instances": "*"},
				{ "Metric": "cpu.corecount.provisioned.average", "Instances": "*" }
			]
		},
		{ 
			"ObjectType": [ "VirtualMachine" ], 
			"Definition": [
			{ "Metric": "datastore.datastoreVMObservedLatency.latest", "Instances": "*" }
			]
		},
		{ 
			"ObjectType": [ "HostSystem" ], 
			"Definition": [
				{ "Metric": "disk.maxTotalLatency.latest", "Instances": "" },
				{ "Metric": "disk.numberReadAveraged.average", "Instances": "*" },
				{ "Metric": "disk.numberWriteAveraged.average", "Instances": "*" },
				{ "Metric": "net.throughput.contention.summation", "Instances": "*" }
			]
		},
		{
                        "ObjectType": [ "Datastore" ],
                        "Definition": [
                                { "Metric": "disk.capacity.latest", "Instances": "*" },
                                { "Metric": "disk.used.latest", "Instances": "*" }
                        ]
                }
	]
}

**Comment by Scott-Phosphore** [comment]
Hi,

I have the same issue when trying to connect to an ESXi, but VCenters work fine for me.

**Comment by larsvs** [comment]
I'm trying this with a singel esxi host too and run in to the same issue.
Were you able to resolve this?

**Comment by sofixa** [comment]
@Scott-Phosphore , @larsvs sadly standalone ESXi hosts are not supported since vSphere's Performance Manager API is vCenter only.

@egru do you still have the error with the latest version? Can you connect with the user you're using and read the per VM/host statistics?

**Comment by KletskoekNL** [comment]
Hello,

I think i'm having the same issue trying to connect to vCenter 6.5. I'm running vsphere-influxdb-go on a Windows 10 Pro machine.
Or maybe I'm doing something wrong...

Either way, some help is needed :)

**Output:**
C:\Go\projects\bin>vsphere-influxdb-go.exe -config c:\go\projects\bin\vsphere-influxdb-go.exe.json
2017/10/30 10:05:54 Starting : vsphere-influxdb-go.exe
2017/10/30 10:05:54 connecting to vcenter: xxxxx
2017/10/30 10:05:55 Successfully connected to Influx
2017/10/30 10:05:55 Querying vcenter
2017/10/30 10:05:55 Setting up query inventory of vcenter:  xxxxx
2017/10/30 10:05:55 connecting to vcenter: xxxxx
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x912e0a]

goroutine 1 [running]:
github.com/oxalide/vsphere-influxdb-go/vendor/github.com/vmware/govmomi/property.(*Collector).Retrieve(0xc0426f2188, 0x118de40, 0xc04233c540, 0x11de858, 0x0, 0x0, 0xc0424066f0, 0x3, 0x3, 0x9b0400, ...)
        C:/Go/projects/src/github.com/oxalide/vsphere-influxdb-go/vendor/github.com/vmware/govmomi/property/collector.go:157 +0x51a
main.(*VCenter).Query(0xc0426f7b98, 0xc0420e08a0, 0x1, 0x4, 0xc0421060c0, 0x4, 0x4, 0x3c, 0x0, 0x0, ...)
        C:/Go/projects/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:300 +0x283b
main.queryVCenter(0xc04204e480, 0x19, 0xc04204e460, 0x1b, 0xc0420506e0, 0xc, 0xc04236c660, 0x3, 0x4, 0xc0420e08a0, ...)
        C:/Go/projects/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:738 +0xf9
main.main()
        C:/Go/projects/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:808 +0x7f6

**Config:**
{
	"Domain": "",
	"Interval": 60,
	"VCenters": [
		{ "Username": "xxxxx", "Password": "xxxxx", "Hostname": "xxxxx" }
	],
	"InfluxDB": {
		"Hostname": "xxxxx",
		"Username": "xxxxx",
		"Password": "xxxxx",
		"Database": "vmware_performance"
	},
	"Metrics": [
		{ 
			"ObjectType": [ "VirtualMachine", "HostSystem" ], 
			"Definition": [
				{ "Metric": "cpu.usage.average", "Instances": "*" },
				{ "Metric": "cpu.usage.maximum", "Instances": "*" },
				{ "Metric": "cpu.usagemhz.average", "Instances": "*" },
				{ "Metric": "cpu.usagemhz.maximum", "Instances": "*" },
				{ "Metric": "cpu.wait.summation", "Instances": "*" },
				{ "Metric": "cpu.system.summation", "Instances": "*" },
				{ "Metric": "cpu.ready.summation", "Instances": "*" },
				{ "Metric": "mem.usage.average", "Instances": "*" },
				{ "Metric": "mem.usage.maximum", "Instances": "*" },
				{ "Metric": "mem.consumed.average", "Instances": "*" },
				{ "Metric": "mem.consumed.maximum", "Instances": "*" },
				{ "Metric": "mem.active.average", "Instances": "*" },
				{ "Metric": "mem.active.maximum", "Instances": "*" },
				{ "Metric": "mem.vmmemctl.average", "Instances": "*" },
				{ "Metric": "mem.vmmemctl.maximum", "Instances": "*" },
				{ "Metric": "mem.totalCapacity.average", "Instances": "*" },
				{ "Metric": "net.packetsRx.summation", "Instances": "*" },
			        { "Metric": "net.packetsTx.summation", "Instances": "*" },
				{ "Metric": "net.throughput.usage.average", "Instances": "*" },
				{ "Metric": "net.received.average", "Instances": "*" },
				{ "Metric": "net.transmitted.average", "Instances": "*" },
				{ "Metric": "net.throughput.usage.nfs.average", "Instances": "*" },
				{ "Metric": "datastore.numberReadAveraged.average", "Instances": "*" },
				{ "Metric": "datastore.numberWriteAveraged.average", "Instances": "*" },
				{ "Metric": "datastore.read.average", "Instances": "*" },
				{ "Metric": "datastore.write.average", "Instances": "*" },
				{ "Metric": "datastore.totalReadLatency.average", "Instances": "*" },
				{ "Metric": "datastore.totalWriteLatency.average", "Instances": "*" },
				{ "Metric": "mem.capacity.provisioned.average", "Instances": "*"},
				{ "Metric": "cpu.corecount.provisioned.average", "Instances": "*" }
			]
		},
		{ 
			"ObjectType": [ "VirtualMachine" ], 
			"Definition": [
			{ "Metric": "datastore.datastoreVMObservedLatency.latest", "Instances": "*" }
			]
		},
		{ 
			"ObjectType": [ "HostSystem" ], 
			"Definition": [
				{ "Metric": "disk.maxTotalLatency.latest", "Instances": "" },
				{ "Metric": "disk.numberReadAveraged.average", "Instances": "*" },
				{ "Metric": "disk.numberWriteAveraged.average", "Instances": "*" },
				{ "Metric": "net.throughput.contention.summation", "Instances": "*" }
			]
		},
		{
                        "ObjectType": [ "Datastore" ],
                        "Definition": [
                                { "Metric": "disk.capacity.latest", "Instances": "*" },
                                { "Metric": "disk.used.latest", "Instances": "*" }
                        ]
                }
	]
}

**Edit:**
On the latest ubuntu(17.10) I got the same result...

**Output on ubuntu:**
$GOBIN/vsphere-influxdb-go -config $GOBIN/vsphere-influxdb-go.json
2017/10/30 16:45:39 Starting : vsphere-influxdb-go
2017/10/30 16:45:39 connecting to vcenter: XXXXXX
2017/10/30 16:45:39 Successfully connected to Influx
2017/10/30 16:45:39 Querying vcenter
2017/10/30 16:45:39 Setting up query inventory of vcenter:  XXXXXX
2017/10/30 16:45:39 connecting to vcenter: XXXXXX
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x913783]

goroutine 1 [running]:
github.com/oxalide/vsphere-influxdb-go/vendor/github.com/vmware/govmomi/property.(*Collector).Retrieve(0xc42020c188, 0x119f3c0, 0xc42044cdc0, 0x11f24c8, 0x0, 0x0, 0xc42031c9f0, 0x3, 0x3, 0x9b2060, ...)
	/root/go/src/github.com/oxalide/vsphere-influxdb-go/vendor/github.com/vmware/govmomi/property/collector.go:157 +0x513
main.(*VCenter).Query(0xc420211b98, 0xc4200d04a0, 0x1, 0x4, 0xc4200f00c0, 0x4, 0x4, 0x3c, 0x0, 0x0, ...)
	/root/go/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:300 +0x2834
main.queryVCenter(0xc42001a8b0, 0xd, 0xc420016580, 0x1b, 0xc42001a8a0, 0xc, 0xc4202dc5e0, 0x3, 0x4, 0xc4200d04a0, ...)
	/root/go/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:738 +0xf2
main.main()
	/root/go/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:808 +0x7ef

**Comment by sofixa** [comment]
@KletskoekNL @egru you're both on vCenter 6.5? After poking around the code and govmomi, it seems that it fails (brutally) when getting the clusters; can you tell me more about yours? I mean, are your hosts in clusters, how many clusters, how many hosts per clusters, something specific(no HA, no DRS enabled), etc?

If i had to guess, i'd say both of you don't have a cluster configured? If that's the case, i'd have to add some conditions to get around it for cases like yours.

**Comment by PenChien** [comment]
hope support esxi

**Comment by egru** [comment]
I am running vCenter 6.5, but not in any clusters.

**Comment by KletskoekNL** [comment]
We have a single center 6.5 with a license for 3 esxi machines and no HA or DRS or other special settings that i know off...

We also have some standalone esxi machines..

**Comment by sofixa** [comment]
Okay, that should be the problem. 

Actually standalone ESXi hosts are supported, but not all metrics are available(notably the provisioning stats), however ESXi hosts not in a cluster under a vCenter aren't; I'll try to find some workaround to make that work.

**Comment by sofixa** [comment]
@KletskoekNL @egru @PenChien Could you try the [latest version, 0.8.1](https://github.com/Oxalide/vsphere-influxdb-go/releases/tag/v0.8.1) ? It should work fine with standalone ESXi hosts, and ESXi hosts under a vCenter without a cluster.

**Comment by KletskoekNL** [comment]
Awesome! Can't wait to try the new version. Will be the first thing i'll do tomorrow!

Thank you so much!

**Comment by KletskoekNL** [comment]
Ok, I tested the new version and I can report that all is working fine when collecting data from a vCenter 6.5 without a cluster, and with a standalone ESXi! :)
Tested with InfluxDB 1.3.7 on Ubuntu 17.10 and Windows 10 Pro(Both with the latest updates)

Many, many Thanks!

**Comment by PenChien** [comment]
I installed vsphere-influxdb-go_0.8.1_linux_amd64.rpm, and it works in ESXi.
Test with influxdb-1.3.7-1.x86_64 on CentOS 7.4, VMware ESXi, 6.5.0, 5310538.

Thanks.
