### ISSUE TITLE
Errors on install

### ISSUE THREAD

**Issue by eringersma** [Oxalide/vsphere-influxdb-go#39]
Go get github.com/oxalide/vsphere-influxdb-go returns 4 errors
(type types.ResourceAllocationInfo has no field or method GetResourceAllocationInfo)
I've been looking at govmomi and it seems they have been changing quite a lot. (pointers converted to non-pointers or vice versa, baseresource was removed)
Is there a specific govmomi release that should be used ?
Will there be a new release of vsphere-influxdb-go that works against the latest vmomi ?

**Comment by Ejant** [comment]
same here....

root@GRAFANA-PLATAFORMAS:/usr/local/go/bin# ./go get github.com/oxalide/vsphere-influxdb-go
# github.com/oxalide/vsphere-influxdb-go
/root/work/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:337:47: pool.Config.MemoryAllocation.GetResourceAllocationInfo undefined (type types.ResourceAllocationInfo has no field or method GetResourceAllocationInfo)
/root/work/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:338:44: pool.Config.CpuAllocation.GetResourceAllocationInfo undefined (type types.ResourceAllocationInfo has no field or method GetResourceAllocationInfo)
/root/work/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:643:46: pool.Config.CpuAllocation.GetResourceAllocationInfo undefined (type types.ResourceAllocationInfo has no field or method GetResourceAllocationInfo)
/root/work/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:644:49: pool.Config.MemoryAllocation.GetResourceAllocationInfo undefined (type types.ResourceAllocationInfo has no field or method GetResourceAllocationInfo)

**Comment by sofixa** [comment]
Sorry, guys! That's what i get for not vendoring. I'll try to rebase to the latest govmomi, and peobably use proper vendoring ASAP.

I suppose govmomi from September should work fine

**Comment by Ejant** [comment]
Thanks!!!!!

**Comment by eringersma** [comment]
I've gone ahead and pulled the 0.12 version of govmomi from github. That version seems to be working !

Tried v0.15 govmomi and that is also not giving the errors.

**Comment by Frank-G** [comment]
How did you go back and use the older version? Create a new repository?

**Comment by eringersma** [comment]
No. If you go to govmomi, click on Branch then on the tab Tags. Dropdown shows latest v0.15. Select that. You can download it and I just put it over the current govmomi directory.
It looks like the VM CPU graphs are working now.
I do not have datastore IO data.
Not sure what the problem is. The user in vcenter has the read-only role. Would think that would work but maybe additional rights are required.
VM CPU, VM Memory, Network is working.
Not getting disk/datastore related graphs. (I'm using Grafana dashboards made by exbane)

**Comment by Frank-G** [comment]
ok, but how do you install it programmatically?
"go get github.com/vmware/govmomi" always use the latest...

**Comment by eringersma** [comment]
wget zipfile. unzip. put over existing govmomi is what I did. A bit crude but works.
This could also work (not tried it):
Run the get command without the tag - it should clone the master branch.
Move to the clone directory and checkout the tag or branch that you want.
Run the go get command again, it should process the command on the checked out branch.

(git clone https://github.com/vmware/govmomi.git
cd govmomi
git checkout tags/v0.15.0
go get github.com/vmware/govmomi
cd  ..go path../github.com/vmware/govmomi
go run govc/main.go version)

**Comment by Ejant** [comment]
@eringersma working here with 0.12 version, no disk graphs

**Comment by Frank-G** [comment]
Have you checked 0.15.0 for disk graphs?

We probably have to go back commit by commit to get the latest stable...

**Comment by Frank-G** [comment]
@eringersma Thanks! I managed to get 0.15.0 to work in a Docker container with these lines:

RUN go get github.com/vmware/govmomi
RUN cd /go/src/github.com/vmware/govmomi && git checkout tags/v0.15.0

still a bit hacky but it seems to work...

**Comment by Ejant** [comment]
@Frank-G it did work with version 0.15 but no disk metrics, it seems that "virtualdisk" metrics are missing. Maybe something missing on my .json file? I've copied example json.
I'm using this dashboard for grafana

https://grafana.com/dashboards/1299

**Comment by eringersma** [comment]
Yes, that's what I figured out too. I've changed the dashboard to use virtualmachine datastore metrics.
The fields I found in the influxdb are
datastore_numberreadaveraged_average
datastore_numberwriteaveraged_average
datastore_read_average
datastore_totalreadlatency_average
datastore_totalwritelatency_avergage
datastore_write_average
No virtualdisk.
You get things like this in the json (virtualdisk replaced by virtualmachine, virtualdisk_ replaced by datastore_:
 "measurement": "virtualmachine",
              "policy": "default",
              "refId": "A",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "datastore_numberreadaveraged_average"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [],
                    "type": "sum"
                  }
                ]

Also the cpu_ready% is now cpu_ready_summation in the database.
I'm not sure what is going on. I thought the dashboard and this oxalide were meant to be used together but it looks like they grew apart.

**Comment by eringersma** [comment]
The storage IO panel I changed looks like this (but in our situation I've removed the lower panel to stop the page from crashing)
`{
  "__inputs": [
    {
      "name": "DS_PEGASUS",
      "label": "InfluxDB",
      "description": "InfluxDB 1.1 ",
      "type": "datasource",
      "pluginId": "influxdb",
      "pluginName": "InfluxDB"
    }
  ],
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "4.2.0-pre1"
    },
    {
      "type": "panel",
      "id": "graph",
      "name": "Graph",
      "version": ""
    },
    {
      "type": "datasource",
      "id": "influxdb",
      "name": "InfluxDB",
      "version": "1.0.0"
    },
    {
      "type": "panel",
      "id": "singlestat",
      "name": "Singlestat",
      "version": ""
    }
  ],
  "annotations": {
    "list": []
  },
  "editable": true,
  "gnetId": 1302,
  "graphTooltip": 1,
  "hideControls": false,
  "id": null,
  "links": [
    {
      "asDropdown": true,
      "icon": "external link",
      "tags": [
        "vmware"
      ],
      "title": "VMware Dashboards",
      "type": "dashboards"
    }
  ],
  "refresh": "5m",
  "rows": [
    {
      "collapse": false,
      "height": "250px",
      "panels": [
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": false,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "datasource": "${DS_PEGASUS}",
          "editable": true,
          "error": false,
          "format": "none",
          "gauge": {
            "maxValue": 100000,
            "minValue": 0,
            "show": true,
            "thresholdLabels": false,
            "thresholdMarkers": true
          },
          "id": 8,
          "interval": null,
          "links": [],
          "mappingType": 1,
          "mappingTypes": [
            {
              "name": "value to text",
              "value": 1
            },
            {
              "name": "range to text",
              "value": 2
            }
          ],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": " wps",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "rangeMaps": [
            {
              "from": "null",
              "text": "N/A",
              "to": "null"
            }
          ],
          "span": 6,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": true
          },
          "targets": [
            {
              "alias": "$tag_cluster",
              "dsType": "influxdb",
              "groupBy": [
                {
                  "params": [
                    "$interval"
                  ],
                  "type": "time"
                },
                {
                  "params": [
                    "cluster"
                  ],
                  "type": "tag"
                },
                {
                  "params": [
                    "null"
                  ],
                  "type": "fill"
                }
              ],
              "measurement": "virtualmachine",
              "policy": "default",
              "refId": "A",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "datastore_numberwriteaveraged_average"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [],
                    "type": "sum"
                  }
                ]
              ],
              "tags": [
                {
                  "key": "host",
                  "operator": "=~",
                  "value": "/^$vCenter$/"
                },
                {
                  "condition": "AND",
                  "key": "cluster",
                  "operator": "=~",
                  "value": "/^$Cluster$/"
                }
              ]
            }
          ],
          "thresholds": "",
          "title": "Total Cluster Write IO",
          "transparent": true,
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "avg"
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": false,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "datasource": "${DS_PEGASUS}",
          "editable": true,
          "error": false,
          "format": "none",
          "gauge": {
            "maxValue": 100000,
            "minValue": 0,
            "show": true,
            "thresholdLabels": false,
            "thresholdMarkers": true
          },
          "id": 2,
          "interval": null,
          "links": [],
          "mappingType": 1,
          "mappingTypes": [
            {
              "name": "value to text",
              "value": 1
            },
            {
              "name": "range to text",
              "value": 2
            }
          ],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": " rps",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "rangeMaps": [
            {
              "from": "null",
              "text": "N/A",
              "to": "null"
            }
          ],
          "span": 6,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": true
          },
          "targets": [
            {
              "alias": "$tag_cluster",
              "dsType": "influxdb",
              "groupBy": [
                {
                  "params": [
                    "$interval"
                  ],
                  "type": "time"
                },
                {
                  "params": [
                    "cluster"
                  ],
                  "type": "tag"
                },
                {
                  "params": [
                    "null"
                  ],
                  "type": "fill"
                }
              ],
              "measurement": "virtualmachine",
              "policy": "default",
              "refId": "A",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "datastore_numberreadaveraged_average"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [],
                    "type": "sum"
                  }
                ]
              ],
              "tags": [
                {
                  "key": "host",
                  "operator": "=~",
                  "value": "/^$vCenter$/"
                },
                {
                  "condition": "AND",
                  "key": "cluster",
                  "operator": "=~",
                  "value": "/^$Cluster$/"
                }
              ]
            }
          ],
          "thresholds": "",
          "title": "Total Cluster Read IO",
          "transparent": true,
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "avg"
        }
      ],
      "repeat": null,
      "repeatIteration": null,
      "repeatRowId": null,
      "showTitle": false,
      "title": "New row",
      "titleSize": "h6"
    },
    {
      "collapse": false,
      "height": "250px",
      "panels": [
        {
          "aliasColors": {},
          "bars": false,
          "datasource": "${DS_PEGASUS}",
          "editable": true,
          "error": false,
          "fill": 1,
          "id": 1,
          "legend": {
            "alignAsTable": true,
            "avg": false,
            "current": false,
            "max": true,
            "min": false,
            "rightSide": true,
            "show": true,
            "sort": "max",
            "sortDesc": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 2,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 6,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "alias": "$tag_name",
              "dsType": "influxdb",
              "groupBy": [
                {
                  "params": [
                    "$interval"
                  ],
                  "type": "time"
                },
                {
                  "params": [
                    "name"
                  ],
                  "type": "tag"
                },
                {
                  "params": [
                    "null"
                  ],
                  "type": "fill"
                }
              ],
              "measurement": "virtualmachine",
              "policy": "default",
              "refId": "A",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "datastore_numberwriteaveraged_average"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [],
                    "type": "sum"
                  }
                ]
              ],
              "tags": [
                {
                  "key": "host",
                  "operator": "=~",
                  "value": "/^$vCenter$/"
                },
                {
                  "condition": "AND",
                  "key": "cluster",
                  "operator": "=~",
                  "value": "/^$Cluster$/"
                },
                {
                  "condition": "AND",
                  "key": "name",
                  "operator": "=~",
                  "value": "/^$vmname$/"
                }
              ]
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeShift": null,
          "title": "VM Write IO",
          "tooltip": {
            "msResolution": false,
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "wps",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ]
        },
        {
          "aliasColors": {},
          "bars": false,
          "datasource": "${DS_PEGASUS}",
          "editable": true,
          "error": false,
          "fill": 1,
          "id": 6,
          "legend": {
            "alignAsTable": true,
            "avg": false,
            "current": false,
            "max": true,
            "min": false,
            "rightSide": true,
            "show": true,
            "sort": "max",
            "sortDesc": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 2,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 6,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "alias": "$tag_name",
              "dsType": "influxdb",
              "groupBy": [
                {
                  "params": [
                    "$interval"
                  ],
                  "type": "time"
                },
                {
                  "params": [
                    "name"
                  ],
                  "type": "tag"
                },
                {
                  "params": [
                    "null"
                  ],
                  "type": "fill"
                }
              ],
              "measurement": "virtualmachine",
              "policy": "default",
              "refId": "A",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "datastore_numberreadaveraged_average"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [],
                    "type": "sum"
                  }
                ]
              ],
              "tags": [
                {
                  "key": "host",
                  "operator": "=~",
                  "value": "/^$vCenter$/"
                },
                {
                  "condition": "AND",
                  "key": "cluster",
                  "operator": "=~",
                  "value": "/^$Cluster$/"
                },
                {
                  "condition": "AND",
                  "key": "name",
                  "operator": "=~",
                  "value": "/^$vmname$/"
                }
              ]
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeShift": null,
          "title": "VM Read IO",
          "tooltip": {
            "msResolution": false,
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "wps",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ]
        },
        {
          "aliasColors": {},
          "bars": false,
          "datasource": "${DS_PEGASUS}",
          "editable": true,
          "error": false,
          "fill": 1,
          "id": 4,
          "legend": {
            "alignAsTable": true,
            "avg": false,
            "current": false,
            "max": true,
            "min": false,
            "rightSide": true,
            "show": true,
            "sort": "max",
            "sortDesc": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 2,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 12,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "alias": "$tag_name",
              "dsType": "influxdb",
              "groupBy": [
                {
                  "params": [
                    "$interval"
                  ],
                  "type": "time"
                },
                {
                  "params": [
                    "name"
                  ],
                  "type": "tag"
                },
                {
                  "params": [
                    "null"
                  ],
                  "type": "fill"
                }
              ],
              "measurement": "virtualmachine",
              "policy": "default",
              "refId": "A",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "datastore_write_average"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [],
                    "type": "sum"
                  }
                ]
              ],
              "tags": [
                {
                  "key": "host",
                  "operator": "=~",
                  "value": "/^$vCenter$/"
                },
                {
                  "condition": "AND",
                  "key": "cluster",
                  "operator": "=~",
                  "value": "/^$Cluster$/"
                },
                {
                  "condition": "AND",
                  "key": "name",
                  "operator": "=~",
                  "value": "/^$vmname$/"
                }
              ]
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeShift": null,
          "title": "VM Write Throughput",
          "tooltip": {
            "msResolution": false,
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "transparent": true,
          "type": "graph",
          "xaxis": {
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "KBs",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ]
        },
        {
          "aliasColors": {},
          "bars": false,
          "datasource": "${DS_PEGASUS}",
          "editable": true,
          "error": false,
          "fill": 1,
          "id": 5,
          "legend": {
            "alignAsTable": true,
            "avg": false,
            "current": false,
            "max": true,
            "min": false,
            "rightSide": true,
            "show": true,
            "sort": "max",
            "sortDesc": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 2,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 12,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "alias": "$tag_name",
              "dsType": "influxdb",
              "groupBy": [
                {
                  "params": [
                    "$interval"
                  ],
                  "type": "time"
                },
                {
                  "params": [
                    "name"
                  ],
                  "type": "tag"
                },
                {
                  "params": [
                    "null"
                  ],
                  "type": "fill"
                }
              ],
              "measurement": "virtualmachine",
              "policy": "default",
              "refId": "A",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "datastore_read_average"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [],
                    "type": "sum"
                  }
                ]
              ],
              "tags": [
                {
                  "key": "host",
                  "operator": "=~",
                  "value": "/^$vCenter$/"
                },
                {
                  "condition": "AND",
                  "key": "cluster",
                  "operator": "=~",
                  "value": "/^$Cluster$/"
                },
                {
                  "condition": "AND",
                  "key": "name",
                  "operator": "=~",
                  "value": "/^$vmname$/"
                }
              ]
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeShift": null,
          "title": "VM Read Throughput",
          "tooltip": {
            "msResolution": false,
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "transparent": true,
          "type": "graph",
          "xaxis": {
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "KBs",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ]
        },
        {
          "aliasColors": {},
          "bars": false,
          "datasource": "${DS_PEGASUS}",
          "editable": true,
          "error": false,
          "fill": 1,
          "id": 3,
          "legend": {
            "alignAsTable": true,
            "avg": false,
            "current": false,
            "max": true,
            "min": false,
            "rightSide": true,
            "show": true,
            "sort": "max",
            "sortDesc": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 2,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 6,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "alias": "$tag_name",
              "dsType": "influxdb",
              "groupBy": [
                {
                  "params": [
                    "$interval"
                  ],
                  "type": "time"
                },
                {
                  "params": [
                    "name"
                  ],
                  "type": "tag"
                },
                {
                  "params": [
                    "null"
                  ],
                  "type": "fill"
                }
              ],
              "measurement": "virtualmachine",
              "policy": "default",
              "refId": "A",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "datastore_numberwriteaveraged_average"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [
                      "90"
                    ],
                    "type": "percentile"
                  }
                ]
              ],
              "tags": [
                {
                  "key": "host",
                  "operator": "=~",
                  "value": "/^$vCenter$/"
                },
                {
                  "condition": "AND",
                  "key": "cluster",
                  "operator": "=~",
                  "value": "/^$Cluster$/"
                },
                {
                  "condition": "AND",
                  "key": "name",
                  "operator": "=~",
                  "value": "/^$vmname$/"
                }
              ]
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeShift": null,
          "title": "VM Write 90th Percentile",
          "tooltip": {
            "msResolution": false,
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "transparent": true,
          "type": "graph",
          "xaxis": {
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "wps",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ]
        },
        {
          "aliasColors": {},
          "bars": false,
          "datasource": "${DS_PEGASUS}",
          "editable": true,
          "error": false,
          "fill": 1,
          "id": 7,
          "legend": {
            "alignAsTable": true,
            "avg": false,
            "current": false,
            "max": true,
            "min": false,
            "rightSide": true,
            "show": true,
            "sort": "max",
            "sortDesc": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 2,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 6,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "alias": "$tag_name",
              "dsType": "influxdb",
              "groupBy": [
                {
                  "params": [
                    "$interval"
                  ],
                  "type": "time"
                },
                {
                  "params": [
                    "name"
                  ],
                  "type": "tag"
                },
                {
                  "params": [
                    "null"
                  ],
                  "type": "fill"
                }
              ],
              "measurement": "virtualmachine",
              "policy": "default",
              "refId": "A",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "datastore_numberreadaveraged_average"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [
                      "90"
                    ],
                    "type": "percentile"
                  }
                ]
              ],
              "tags": [
                {
                  "key": "host",
                  "operator": "=~",
                  "value": "/^$vCenter$/"
                },
                {
                  "condition": "AND",
                  "key": "cluster",
                  "operator": "=~",
                  "value": "/^$Cluster$/"
                },
                {
                  "condition": "AND",
                  "key": "name",
                  "operator": "=~",
                  "value": "/^$vmname$/"
                }
              ]
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeShift": null,
          "title": "VM Read 90th Percentile",
          "tooltip": {
            "msResolution": false,
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "transparent": true,
          "type": "graph",
          "xaxis": {
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "wps",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ]
        }
      ],
      "repeat": null,
      "repeatIteration": null,
      "repeatRowId": null,
      "showTitle": false,
      "title": "New row",
      "titleSize": "h6"
    }
  ],
  "schemaVersion": 14,
  "style": "dark",
  "tags": [
    "vmware",
    "golang",
    "influxdb"
  ],
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {},
        "datasource": "${DS_PEGASUS}",
        "hide": 0,
        "includeAll": false,
        "label": null,
        "multi": false,
        "name": "vCenter",
        "options": [],
        "query": "SHOW TAG VALUES FROM \"virtualmachine\" with key = \"host\"",
        "refresh": 1,
        "regex": "",
        "sort": 0,
        "tagValuesQuery": null,
        "tags": [],
        "tagsQuery": null,
        "type": "query",
        "useTags": false
      },
      {
        "allValue": null,
        "current": {},
        "datasource": "${DS_PEGASUS}",
        "hide": 0,
        "includeAll": false,
        "label": "Cluster",
        "multi": false,
        "name": "Cluster",
        "options": [],
        "query": "SHOW TAG VALUES FROM \"virtualmachine\" with key = \"cluster\" WHERE \"host\" =~ /^$vCenter$/",
        "refresh": 1,
        "regex": "",
        "sort": 0,
        "tagValuesQuery": null,
        "tags": [],
        "tagsQuery": null,
        "type": "query",
        "useTags": false
      },
      {
        "allValue": null,
        "current": {},
        "datasource": "${DS_PEGASUS}",
        "hide": 2,
        "includeAll": true,
        "label": "Virtual Machine",
        "multi": false,
        "name": "vmname",
        "options": [],
        "query": "SHOW TAG VALUES FROM \"virtualmachine\" WITH KEY = \"name\" where \"host\" =~ /^$vCenter$/",
        "refresh": 1,
        "regex": "",
        "sort": 0,
        "tagValuesQuery": null,
        "tags": [],
        "tagsQuery": null,
        "type": "query",
        "useTags": false
      }
    ]
  },
  "time": {
    "from": "now-24h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "browser",
  "title": "VMware Performance: Storage IO",
  "version": 14,
  "description": "Storage IO for Clusters and VMs"
}`

**Comment by Ejant** [comment]
Thanks everyone!!!!

**Comment by sofixa** [comment]
@Frank-G @Ejant @eringersma vendoring is in place, just go getting the project should compile just fine now. Sorry for the wait and issues, it shouldn't happen anymore :)

As for @exbane 's dashboard on grafana.org, it works if you have all the metrics needed defined in your .json conf, there's a full list here - http://www.virten.net/2015/05/vsphere-6-0-performance-counter-description/ . I'll upload two more dashboards ASAP, and i'm also working on making GitHub releases with at least the binary, that way it will be much easier for people to start using this tool.

Cheers,
Adrian

**Comment by sofixa** [comment]
Update: I've uploaded a dashboard on grafana.com - https://grafana.com/dashboards/3556

**Comment by sofixa** [comment]
Update2: I've uploaded another dashboard on grafan.com - https://grafana.com/dashboards/3571

**Comment by eringersma** [comment]
I get a URI too long 414 error although the apache already has 100.000 LimitRequestLine. 120.000 was not enough zo increased it to 150.000.
Beside that I don't get the graph. The query executed is
SELECT mean("datastore_numberreadaveraged_average") FROM /cpu$/ WHERE ("name"=~ [followed by all vm's that cause the long line]
There is no such field in CPU.  There is a field in influxdb under virtualmachine but it has no values in my case.

**Comment by sofixa** [comment]
For the request URI too long, you need to go in the templating settings of your dashboard, and add a "Custom All value" /.*/ on all variables that can become too long. I should add that to a FAQ or something.
As for the missing data, i'll respond in the other issue a bit later, but could you try just exploring your influxdb data locally(with the influx cli), doing show measurements, show series on the database (by default vmware_performance)?

**Comment by eringersma** [comment]
I tried that Custom All value but it didn't work. I got an error about . expecting ;
Grafana used is version 4.5.2
I get measurements and show series.
When I look at virtualmachine field datastore_numberreadaveraged_average the series is empty. That object is declared in vsphere-influxdb-go.json. It is present in the influxdb database. But it does not contain values. If I look at vsphere client I can find a numberReadAveraged field in performance under datastore (collection level 1)

**Comment by sofixa** [comment]
Actually you need collection level 4 on collection interval 1(with id 60, the default one in the json). Sorry if i wasn't clear enough, the terminology is a bit weird.

**Comment by eringersma** [comment]
The 5 minute collection (interval 1) is set on level 4 in vCenter settings.
All settings:
Interval 5 minutes : level 4
Interval 30 minutes: level 3
Interval 2 hours: level 2
Interval 1 day: level 1
I'd expect that to be fine with default 60 seconds interval. (running collector via crontab every minute)
