### ISSUE TITLE
Logon Issue

### ISSUE THREAD

**Issue by BHB3805** [Oxalide/vsphere-influxdb-go#40]
I'm having issues logging in.

My vCenter name is vcsa01.a10x.net running VCSA 6.5 U1
My vCenter login account is administrator@vsphere.local
 
Here's part of the configuration file:

"Domain": "",
"Interval": 60,
 "VCenters": [
                { "Username": "administrator@vsphere.local", "Password": "Ex1234$$, "Hostname": "vcsa01.a10x.net" }
],

I receive the following error message:

2017/10/25 23:27:28 Starting : vsphere-influxdb-go
2017/10/25 23:27:28 connecting to vcenter: vcsa01.a10x.net
2017/10/25 23:27:28 Could not connect to vcenter:  vcsa01.a10x.net
2017/10/25 23:27:28 Error:  Post https://vcsa01.a10x.net/sdk: Not Found
2017/10/25 23:27:28 Could not connect to vcenter:  a02pvcsa01.bhbank.net
2017/10/25 23:27:28 Error:  Post https://vcsa01.a10x.net/sdk: Not Found
2017/10/25 23:27:28 Successfully connected to Influx
2017/10/25 23:27:28 Querying vcenter
2017/10/25 23:27:28 Setting up query inventory of vcenter:  vcsa01.a10x.net
2017/10/25 23:27:28 connecting to vcenter: vcsa01.a10x.net
2017/10/25 23:27:28 Could not connect to vcenter:  vcsa01.a10x.net
2017/10/25 23:27:28 Error:  Post https://vcsa01.a10x.net: Not Found
2017/10/25 23:27:28 Could not connect to vcenter:  vcsa01.a10x.net
2017/10/25 23:27:28 Error:  Post https://vcsa01.a10x.net: Not Found

Any ideas?

**Comment by eringersma** [comment]
Looks to me like a nslookup issue. Can you ping vcsa01.a10x.net ? Will it give an ip-address ?

**Comment by sofixa** [comment]
Yeah, seems like a networking issue.
Can you nslookup the domain? If yes, can you telnet port 443 on it? If yes, can you wget/curl https://vcsa01.a10x.net/sdk ? All from the machine you're running vsphere-influxdb-go.
