### ISSUE TITLE
Some dashboard panels show N/A

### ISSUE THREAD

**Issue by eringersma** [Oxalide/vsphere-influxdb-go#41]
Thanks for the update.
Nice dashboard. However the first panels show N/A.
VM Number is based on cpu_corecount_provisioned_average. I'm confused. That only count the number of assigned vCPU's ? Not really VM number ?
Anyway that is N/A. vCPU provisioned is N/A. vCPU available is N/A.
The cpu.corecount.provisioned.average is declared in the influxdb-go.json under virtualmachine so that looks ok. However when I look at the influxdb it does not show the field.
Total RAM available is N/A. However in the influxdb-go.json under object-type VirtualMachine,HostSystem there is a declaration of mem.totalCapacity.average.

Also the total amount of memory seems to be 10x bigger than expected. 
(I have not updated the influxdb-go because it looks like only the install is changed to get the right version of govmomi which is nice)

**Comment by sofixa** [comment]
I should add that to the README, but all those *provisioned* stats need the level 4 of metric collection on the vCenter. More info here - http://www.virten.net/2015/05/which-performance-counters-are-available-in-each-statistic-level/

To change the current level on your vCenter, there is this script http://www.valcolabs.com/2012/02/06/modify-historical-statistics-level-using-powercli/ in powercli and i have a pyvmomi version i will upload today, along with another dashboard which is more focused on a per-VM(or muli-VM) view.

Adrian

**Comment by eringersma** [comment]
I've increased the 5minute stats from 3 to 4 on the vCenter. This does not fix all N/A. (It's been 1.5 hours ago that I increased the stats level so I would expect it to have been filled in by now)
The script is running every minute so I would expect 5minute stats (kept for 1 day) to be sufficient.
For exampe the Total ram available in GB is based on hostsystem/mem_totalcapacity_averaga
Counter is available in vsphere-influxdb-go.json. (and I can also see mem_totalcapacity_average in influxdb)
Not sure what's going wrong.

(edit: It looks like the name = regular expression does not go well. removed it and got values)
Edwin

**Comment by sofixa** [comment]
Yeah, in InfluxDB name is a somewhat special word, you have to double quote it to search. 
In your .json conf what is the Interval value? When you manually do the requests in InfluxDB that you see in Grafana, do you get the data? If yes, are you sure you're on the correct datasource ?

**Comment by eringersma** [comment]
The json file used is the stock example json with interval 60.
I'm talking against a VC 6.0. The dropdown esx has no server names, just ALL (which is fine for me)
The name taken is empty and the select statement is not returning a result.

**Comment by sofixa** [comment]
@eringersma could you provide me with the following:

* a (sanitized, of course ) version of your .json config
* the output of running the binary with -debug flag
* the output of the following commands in your influxdb:

```
use database_in_your_json
show measurements
show series
```

I'll try to add some more verbose options soon to make it easier to debug situations like yours.

**Comment by eringersma** [comment]
cat /etc/vsphere-influxdb-go.json
{
        "Domain": ".lab",
        "Interval": 60,
        "VCenters": [
                { "Username": "beheer\\oxalide", "Password": "password", "Hostname": "vc-svr02.beheer.local" }

        ],
        "InfluxDB": {
                "Hostname": "http://192.168.160.61:8086",
                "Username": "grafana",
                "Password": "password",
                "Database": "vmwaredb"
        },
        "Metrics": [
                {
                        "ObjectType": [ "VirtualMachine", "HostSystem" ],
                        "Definition": [
                                { "Metric": "cpu.usage.average", "Instances": "*" },
                                { "Metric": "cpu.usage.maximum", "Instances": "*" },
                                { "Metric": "cpu.usagemhz.average", "Instances": "*" },
                                { "Metric": "cpu.usagemhz.maximum", "Instances": "*" },
                                { "Metric": "cpu.wait.summation", "Instances": "*" },
                                { "Metric": "cpu.system.summation", "Instances": "*" },
                                { "Metric": "cpu.ready.summation", "Instances": "*" },
                                { "Metric": "mem.usage.average", "Instances": "*" },
                                { "Metric": "mem.usage.maximum", "Instances": "*" },
                                { "Metric": "mem.consumed.average", "Instances": "*" },
                                { "Metric": "mem.consumed.maximum", "Instances": "*" },
                                { "Metric": "mem.active.average", "Instances": "*" },
                                { "Metric": "mem.active.maximum", "Instances": "*" },
                                { "Metric": "mem.vmmemctl.average", "Instances": "*" },
                                { "Metric": "mem.vmmemctl.maximum", "Instances": "*" },
                                { "Metric": "mem.totalCapacity.average", "Instances": "*" },
                                { "Metric": "net.packetsRx.summation", "Instances": "*" },
                                { "Metric": "net.packetsTx.summation", "Instances": "*" },
                                { "Metric": "net.throughput.usage.average", "Instances": "*" },
                                { "Metric": "net.received.average", "Instances": "*" },
                                { "Metric": "net.transmitted.average", "Instances": "*" },
                                { "Metric": "net.throughput.usage.nfs.average", "Instances": "*" },
                                { "Metric": "datastore.numberReadAveraged.average", "Instances": "*" },
                                { "Metric": "datastore.numberWriteAveraged.average", "Instances": "*" },
                                { "Metric": "datastore.read.average", "Instances": "*" },
                                { "Metric": "datastore.write.average", "Instances": "*" },
                                { "Metric": "datastore.totalReadLatency.average", "Instances": "*" },
                                { "Metric": "virtualDisk.readOIO.latest", "Instances": "*" },
                                { "Metric": "virtualDisk.writeOIO.latest", "Instances": "*" },
                                { "Metric": "datastore.totalWriteLatency.average", "Instances": "*" },
                                { "Metric": "mem.capacity.provisioned.average", "Instances": "*"},
                                { "Metric": "cpu.corecount.provisioned.average", "Instances": "*" },
                                { "Metric": "cpu.corecount.total", "Instances": "*" }
                        ]
                },
                {
                        "ObjectType": [ "VirtualMachine" ],
                        "Definition": [
                        { "Metric": "datastore.datastoreVMObservedLatency.latest", "Instances": "*" }
                        ]
                },
                {
                        "ObjectType": [ "HostSystem" ],
                        "Definition": [
                                { "Metric": "disk.maxTotalLatency.latest", "Instances": "" },
                                { "Metric": "disk.numberReadAveraged.average", "Instances": "*" },
                                { "Metric": "disk.numberWriteAveraged.average", "Instances": "*" },
                                { "Metric": "net.throughput.contention.summation", "Instances": "*" }
                        ]
                },
                {
                        "ObjectType": [ "Datastore" ],
                        "Definition": [
                                { "Metric": "disk.capacity.latest", "Instances": "*" },
                                { "Metric": "disk.used.latest", "Instances": "*" }
                        ]
                }
        ]
}

**Comment by eringersma** [comment]
Show series is a long list, I'm reluctant to release. lines like this.
virtualmachine,cluster=Cluster-PR1,datastore=cld_winvol201,esx=prev-esx-a02.beheer.local,host=vc-svr02.beheer.local,name=expa00_pvkpnbfil01_000004,respool=Resources
virtualmachine,cluster=Cluster-PR1,datastore=cld_winvol201,esx=prev-esx-a02.beheer.local,host=vc-svr02.beheer.local,name=expa00_pvtmobfil01_000009,respool=Resources
virtualmachine,cluster=Cluster-PR1,datastore=cld_winvol201,esx=prev-esx-a02.beheer.local,host=vc-svr02.beheer.local,name=expa00_vlv000001_000032,respool=Resources
virtualmachine,cluster=Cluster-PR1,datastore=cld_winvol201,esx=prev-esx-a02.beheer.local,host=vc-svr02.beheer.local,name=expa00_vlv000005_000035,respool=Resources

**Comment by eringersma** [comment]
> show measurements
name: measurements
name
----
cpu
datastore
disk
hostsystem
net
resourcepool
virtualdisk
virtualmachine

**Comment by eringersma** [comment]
Debug is panicing
2017/11/02 08:58:10 VirtualMachine:vm-108783
2017/11/02 08:58:10 --VM ID - you should see every VM ID here--
2017/11/02 08:58:10 VirtualMachine:vm-101807
2017/11/02 08:58:10 --VM ID - you should see every VM ID here--
2017/11/02 08:58:10 VirtualMachine:vm-115240
2017/11/02 08:58:10 --VM ID - you should see every VM ID here--
2017/11/02 08:58:10 VirtualMachine:vm-111290
2017/11/02 08:58:10 going inside clusters
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x919716]

goroutine 1 [running]:
main.(*VCenter).Query(0xc420385b98, 0xc4200fe480, 0x1, 0x4, 0xc42011e0c0, 0x4, 0x4, 0x3c, 0xc42008e738, 0x4, ...)
        /root/work/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:383 +0x2e46
main.queryVCenter(0xc42009e3c0, 0x15, 0xc42008e7c0, 0xe, 0xc42009e3a0, 0x18, 0xc4202dad20, 0x3, 0x4, 0xc4200fe480, ...)
        /root/work/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:738 +0xf2
main.main()
        /root/work/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:808 +0x7ef

**Comment by eringersma** [comment]
Hmm. I broke the machine. The disk had filled up because influxdb was installed on /var/lib on the / mount which wasn't that big. Moved it and now the -debug does not report errors anymore.
However grafana startpage thinks it's fresh install (but direct links to dashboard do still work)

Edit: forgot to mention: the error was gone after diskspace was back to normal again.

**Comment by eringersma** [comment]
When the VC is selected the host dropdown only has All. No specific ESX hosts. The name=/^$esx$/ returns nothing. So the graphs are empty vCPU availabe/provisioned stay empty.

**Comment by sofixa** [comment]
Hmmmm. 

Can you run the following and provide me the sanitized outputs?

```
show series from hostsystem
```


When you manually do the query to get esx hosts, do you have results?

```
show tag values from hostsystem with key = "name" where host =~ /vc-svr02.beheer.local/
```

Btw are you running different specific retention policies?

**Comment by eringersma** [comment]
> show series from hostsystem
key
---
hostsystem,cluster=Deployment,host=vc-svr02.beheer.local,name=prev-esx-a29.beheer.local
hostsystem,cluster=Deployment,host=vc-svr02.beheer.local,name=prev-esx-a30.beheer.local
hostsystem,cluster=Deployment,host=vc-svr02.beheer.local,name=prev-esx-b26.beheer.local
hostsystem,cluster=Deployment-zonder-vshield,host=vc-svr02.beheer.local,name=prev-esx-a29.beheer.local
hostsystem,cluster=Deployment-zonder-vshield,host=vc-svr02.beheer.local,name=prev-esx-a30.beheer.local
hostsystem,cluster=Deployment-zonder-vshield,host=vc-svr02.beheer.local,name=prev-esx-b26.beheer.local
hostsystem,cluster=Deployment-zonder-vshield,host=vc-svr02.beheer.local,name=prev-esx-b27.beheer.local
hostsystem,cluster=Cluster-EX1,host=vc-svr02.beheer.local,name=prev-esx-a11.beheer.local
hostsystem,cluster=Cluster-EX1,host=vc-svr02.beheer.local,name=prev-esx-a12.beheer.local
hostsystem,cluster=Cluster-EX1,host=vc-svr02.beheer.local,name=prev-esx-a13.beheer.local
hostsystem,cluster=Cluster-EX1,host=vc-svr02.beheer.local,name=prev-esx-a14.beheer.local
hostsystem,cluster=Cluster-EX1,host=vc-svr02.beheer.local,name=prev-esx-a15.beheer.local
hostsystem,cluster=Cluster-EX1,host=vc-svr02.beheer.local,name=prev-esx-a16.beheer.local
hostsystem,cluster=Cluster-EX1,host=vc-svr02.beheer.local,name=prev-esx-a17.beheer.local
hostsystem,cluster=Cluster-EX1,host=vc-svr02.beheer.local,name=prev-esx-a18.beheer.local
hostsystem,cluster=Cluster-EX1,host=vc-svr02.beheer.local,name=prev-esx-a19.beheer.local
hostsystem,cluster=Cluster-EX1,host=vc-svr02.beheer.local,name=prev-esx-a20.beheer.local
hostsystem,cluster=Cluster-EX1,host=vc-svr02.beheer.local,name=prev-esx-a21.beheer.local
hostsystem,cluster=Cluster-EX1,host=vc-svr02.beheer.local,name=prev-esx-a22.beheer.local
hostsystem,cluster=Cluster-EX1,host=vc-svr02.beheer.local,name=prev-esx-a25.beheer.local
hostsystem,cluster=Cluster-EX1,host=vc-svr02.beheer.local,name=prev-esx-a26.beheer.local
hostsystem,cluster=Cluster-EX1,host=vc-svr02.beheer.local,name=prev-esx-a27.beheer.local
hostsystem,cluster=Cluster-EX1,host=vc-svr02.beheer.local,name=prev-esx-a28.beheer.local
hostsystem,cluster=Cluster-EX2,host=vc-svr02.beheer.local,name=prev-esx-b11.beheer.local
hostsystem,cluster=Cluster-EX2,host=vc-svr02.beheer.local,name=prev-esx-b12.beheer.local
hostsystem,cluster=Cluster-EX2,host=vc-svr02.beheer.local,name=prev-esx-b13.beheer.local
hostsystem,cluster=Cluster-EX2,host=vc-svr02.beheer.local,name=prev-esx-b14.beheer.local
hostsystem,cluster=Cluster-EX2,host=vc-svr02.beheer.local,name=prev-esx-b15.beheer.local
hostsystem,cluster=Cluster-EX2,host=vc-svr02.beheer.local,name=prev-esx-b16.beheer.local
hostsystem,cluster=Cluster-EX2,host=vc-svr02.beheer.local,name=prev-esx-b17.beheer.local
hostsystem,cluster=Cluster-EX2,host=vc-svr02.beheer.local,name=prev-esx-b18.beheer.local
hostsystem,cluster=Cluster-EX2,host=vc-svr02.beheer.local,name=prev-esx-b19.beheer.local
hostsystem,cluster=Cluster-EX2,host=vc-svr02.beheer.local,name=prev-esx-b20.beheer.local
hostsystem,cluster=Cluster-EX2,host=vc-svr02.beheer.local,name=prev-esx-b21.beheer.local
hostsystem,cluster=Cluster-EX2,host=vc-svr02.beheer.local,name=prev-esx-b22.beheer.local
hostsystem,cluster=Cluster-EX2,host=vc-svr02.beheer.local,name=prev-esx-b25.beheer.local
hostsystem,cluster=Cluster-EX2,host=vc-svr02.beheer.local,name=prev-esx-b26.beheer.local
hostsystem,cluster=Cluster-EX2,host=vc-svr02.beheer.local,name=prev-esx-b28.beheer.local
hostsystem,cluster=Cluster-EX2,host=vc-svr02.beheer.local,name=prev-esx-b29.beheer.local
hostsystem,cluster=Cluster-PR1,host=vc-svr02.beheer.local,name=prev-esx-a01.beheer.local
hostsystem,cluster=Cluster-PR1,host=vc-svr02.beheer.local,name=prev-esx-a02.beheer.local
hostsystem,cluster=Cluster-PR1,host=vc-svr02.beheer.local,name=prev-esx-a03.beheer.local
hostsystem,cluster=Cluster-PR1,host=vc-svr02.beheer.local,name=prev-esx-b01.beheer.local
hostsystem,cluster=Cluster-PR1,host=vc-svr02.beheer.local,name=prev-esx-b02.beheer.local
hostsystem,cluster=Cluster-PR1,host=vc-svr02.beheer.local,name=prev-esx-b03.beheer.local

**Comment by eringersma** [comment]
Retention I'v mentioned before somewhere:
5 min 1 day level 4
30 min 1 week level 3
2 hours 1 month level 2
1 day 1 year level 1

**Comment by eringersma** [comment]
> show tag values from hostsystem with key = "name" where host =~ /vc-svr02.beheer.local/
name: hostsystem
key  value
---  -----
name prev-esx-a01.beheer.local
name prev-esx-a02.beheer.local
name prev-esx-a03.beheer.local
name prev-esx-a11.beheer.local
name prev-esx-a12.beheer.local
name prev-esx-a13.beheer.local
name prev-esx-a14.beheer.local
name prev-esx-a15.beheer.local
name prev-esx-a16.beheer.local
name prev-esx-a17.beheer.local
name prev-esx-a18.beheer.local
name prev-esx-a19.beheer.local
name prev-esx-a20.beheer.local
name prev-esx-a21.beheer.local
name prev-esx-a22.beheer.local
name prev-esx-a25.beheer.local
name prev-esx-a26.beheer.local
name prev-esx-a27.beheer.local
name prev-esx-a28.beheer.local
name prev-esx-a29.beheer.local
name prev-esx-a30.beheer.local
name prev-esx-b01.beheer.local
name prev-esx-b02.beheer.local
name prev-esx-b03.beheer.local
name prev-esx-b11.beheer.local
name prev-esx-b12.beheer.local
name prev-esx-b13.beheer.local
name prev-esx-b14.beheer.local
name prev-esx-b15.beheer.local
name prev-esx-b16.beheer.local
name prev-esx-b17.beheer.local
name prev-esx-b18.beheer.local
name prev-esx-b19.beheer.local
name prev-esx-b20.beheer.local
name prev-esx-b21.beheer.local
name prev-esx-b22.beheer.local
name prev-esx-b25.beheer.local
name prev-esx-b26.beheer.local
name prev-esx-b27.beheer.local
name prev-esx-b28.beheer.local
name prev-esx-b29.beheer.local
>

**Comment by sofixa** [comment]
Sorry, by retention i meant retention policies on the InfluxDB server, discoverable with:

```
show retention policies on my_database
```

**Comment by sofixa** [comment]
Ah, i think i got it, could you screenshot your esx variable configuration ?

**Comment by eringersma** [comment]
name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
autogen 0s       168h0m0s           1        true

Not sure what you want to have screenshotted.

**Comment by sofixa** [comment]
On your dashboard, there's a few buttons next to it's name; the last one is for settings(a little wheel), the second option of its dropdown is Templating. When you click it, you'll have a list of all your templating variables ($host, $esx, $datastore). Can you edit $esx and screenshot the resulting page?

**Comment by eringersma** [comment]
![image](https://user-images.githubusercontent.com/33025203/32536721-ead069aa-c45f-11e7-8ca4-50acbc972f5a.png)

**Comment by sofixa** [comment]
Yeah, i thought so. My bad, i left something custom in the settings. If you remove the /adm/ regex, save and reload, does everything work perfectly?

**Comment by eringersma** [comment]
That resolved the N/A. I'm not sure if the values are correct. VM count does not seem right for example. It looks roughly 10x the number it should be. CPU count is not usable for the counter, should be summation cpu per vm divided by average cpu per vm or something.

**Comment by sofixa** [comment]
What's your default group by time on the datasource level? (Go to datasources, pick the one you're using, it's in the settings at the end).

```
CPU count is not usable for the counter, should be summation cpu per vm divided by average cpu per vm or something.
```

I'm sorry, i'm not sure i understand, could you expand a little?

**Comment by eringersma** [comment]
The time is greyed. 10s it says. That is the default I guess.

The field used for VM's is cpu corecount. However several vm's have more than one vCPU. So this is not really the VM count.

**Comment by sofixa** [comment]
The 10s is just an example, it takes the default value from your datasource settings. If you set it to 60s, it should work as expected.

As for the number of VMs, it does a count on the number of lines with the cpu_corecount_provisioned field, so 1 for every VM, therefore, the total number of VMs.

**Comment by eringersma** [comment]
Somehow the count is way off. Like a factor 10. I would think a count of distinct name would be better. I've changed the _$interval into 1m so a fixed value that matches the polling interval. Now the number seems to be in the same ballpark as I would expect it to be. (Now it's too low for the total vm's)

**Comment by sofixa** [comment]
@eringersma Which version of Grafana are you running? I noticed that after updating, i have the same wrong group by result if using the $interval variable; however, if i statically put group by 1m in in the panel configuration(check below), the value is as expected.

![image](https://user-images.githubusercontent.com/4072680/33098209-e04ed78e-cf0c-11e7-9eee-4c1dc56f35eb.png)

**Comment by eringersma** [comment]
v4.5.2

**Comment by sofixa** [comment]
Have you tried manually setting the Group by time value to 1m/60s ?
