### ISSUE TITLE
Understanding the metrics

### ISSUE THREAD

**Issue by jimr6007** [Oxalide/vsphere-influxdb-go#42]
I think I'm not understanding a concept. 

If all 544 vCenter stats are always available and kept for one hour:
"Realtime (20 seconds), save for 1 hour - not configurable, all metrics available"

Why would I need to change anything if vsphere-influxdb-go is pulling every 5 minutes for example?

Once I have my data in InfluxDB I don't really care if vCenter gets rid of some of that data an hour later. Right?

**Comment by sofixa** [comment]
Yep, but not all metrics are collected by default(the provisioning ones aren't http://www.virten.net/2015/05/which-performance-counters-are-available-in-each-statistic-level/ ), so you need to change the collection level to 4 to get all stats you need(if you need them all of course). 
Just FYI, VCSA 5.5U2 seems to have a hard time with that setting and makes huge spikes in IO write.
