### ISSUE TITLE
"ObjectType" "ClusterComputeResource" in json

### ISSUE THREAD

**Issue by eschek87** [Oxalide/vsphere-influxdb-go#43]
Hi,

I have definied the follwoing in the json config:
"ObjectType": [ "ClusterComputeResource" ],
                        "Definition": [
                        { "Metric": "mem.capacity.provisioned.average", "Instances": "*"},
                        { "Metric": "cpu.corecount.provisioned.average", "Instances": "*" },
                        { "Metric": "vmop.numCreate.latest", "Instances": "*" },
                        { "Metric": "vmop.numPoweroff.latest", "Instances": "*" },
                        { "Metric": "vmop.numPoweron.latest", "Instances": "*" },
                        { "Metric": "vmop.numDestroy.latest", "Instances": "*" },
                        { "Metric": "vmop.numClone.latest", "Instances": "*" },
                        { "Metric": "vmop.numDeploy.latest", "Instances": "*" },
                        { "Metric": "vmop.numVMotion.latest", "Instances": "*" },
                        { "Metric": "vmop.numSVMotion.latest", "Instances": "*" },
                        { "Metric": "vmop.numXVMotion.latest", "Instances": "*" },
                        { "Metric": "mem.capacity.usable.average", "Instances": "*" }
                        ]

But it seems that the metrics where not queried.

**Comment by sofixa** [comment]
Hi, @eschek87 . Could you provide the output of running with the -debug  flag?

**Comment by eschek87** [comment]
Hi, I had redirect the output to debug.log file and remove some company information and logins.
[debug.log](https://github.com/Oxalide/vsphere-influxdb-go/files/1500758/debug.log)

**Comment by sofixa** [comment]
Hi, @eschek87 .

So, the *.provisioned.* and *.capacity.* counters don't exist on the cluster level, but you could easily get the via InfluxDB with a similar query(going from memory):
```
SELECT sum(cpu_corecount_provisioned_average) FROM virtualmachine WHERE time > now() - 1h GROUP BY cluster, time(1m)

```

Or in Grafana, you just need to select he sum of cpu_corecount_provisioned_average from virtualmachine, group by tag cluster and time (60s if you're collecting every 60s).

As for the vmop.* counters, i don't see why they wouldn't work, but they don't (IIRC @exbane tried them a few months ago). I might give it a go some day, but not in the immediate future, however, contributions are welcome if you want to give a hand :)

Cheers,
Adrian
