### ISSUE TITLE
VirtualMachine Datastore performance lost datastore object

### ISSUE THREAD

**Issue by Etuloser** [Oxalide/vsphere-influxdb-go#45]
Hi,

Thank you very much for your tools, but finding problems in use:

My virtualmachine datastore mount multiple datastore, but vsphere-influx-db find only one, performance no yet for missing this datastore, for example latency and ops

**Comment by sofixa** [comment]
Hi, @Etuloser .

If you use the virtualdisk.* performance counters, you'll get the data(latency, ops, throughput, etc.) per virtual disk. 

Adrian
