### ISSUE TITLE
Running as CRON not showing information

### ISSUE THREAD

**Issue by Duglz** [Oxalide/vsphere-influxdb-go#46]
When I run the  `/usr/local/bin/vsphere-influxdb-go` in my CRON my information does not update. When I manually run it it goes just fine.

`crontab -l`
`* * * * * /usr/local/bin/vsphere-influxdb-go > /var/log/influx.log 2>&1`

Output of the log file.

```
2017/12/11 10:00:01 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
2017/12/11 10:00:01 Successfully connected to Influx
2017/12/11 10:00:01 connecting to vcenter: REDACTED
2017/12/11 10:00:02 Setting up query inventory of vcenter:  REDACTED
2017/12/11 10:00:03 248173
2017/12/11 10:00:03 72904
2017/12/11 10:00:03 2019446
2017/12/11 10:00:03 280483
2017/12/11 10:00:05 sent data to Influxdb
```

**Comment by Integrative** [comment]
Had similar issue with http_proxy in /etc/environment, add a no_proxy directive for vcenter(s) and all moves along just fine.

**Comment by sofixa** [comment]
@Duglz , as @Integrative pointed out, it's probably an environment problem - proxy, different user (crontab is under user admin and you launch it manually under root, so the crontab can't write to /var/log/influx.log ), things like that.
