### ISSUE TITLE
grafana dashboard 3571 stops working for certain selects

### ISSUE THREAD

**Issue by dahabakuk** [Oxalide/vsphere-influxdb-go#47]
your linked dashboard stops working after upgrade from influxdb 1.3 to 1.4 for certain selects

https://grafana.com/dashboards/3571

the reason seems to be:

influx 1.4:

SELECT (mean("cpu_ready_summation")  / (60 * 1000) * 100) FROM virtualmachine WHERE "name" =~ /"vmname"/
ERR: cannot perform a binary expression on two literals

vs
SELECT (mean("cpu_ready_summation") *100 / 60000) FROM virtualmachine WHERE "name" =~ /"vmname"/
>

if this is not the right place to report such issues.. sorry! :)

**Comment by dahabakuk** [comment]
the math is wrong, just ignore that ;)

**Comment by sofixa** [comment]
Thanks ! I've updated the dashboard with your revision.

Adrian
