### ISSUE TITLE
after upgrade from vsphere 5 to 6 script errors out

### ISSUE THREAD

**Issue by dahabakuk** [Oxalide/vsphere-influxdb-go#48]
hi,
it seems that something is now broken after the upgrade to vpshere 6:

2017/12/14 13:37:42 going inside clusters
2017/12/14 13:37:43 Could not request perfs from vcenter: vcenter.server.local
2017/12/14 13:37:43 Error:  ServerFaultCode: The object has already been deleted or has not been completely created

but i cannot really understand from that output whats wrong.
we have another vcenter 6 server which does not have this problem...

do you have any ideas how to debu this further?

thanks!

**Comment by sofixa** [comment]
Hi,

Could you run with the -debug flag and paste a sanitized output? That should show the offending moref that it gets stuck on.

Adrian

**Comment by dahabakuk** [comment]
hi,
after patching for meltdown/spectre - the ERROR did go away. it seems there was a problem with one of the clusters
thanks anyways!
