### ISSUE TITLE
ESXi / vCentre uptime

### ISSUE THREAD

**Issue by djrarky** [Oxalide/vsphere-influxdb-go#49]
Hi,

I cannot find a way to pull up-time from this script. Can anyone help?

Kind Regards,
Steven

**Comment by sofixa** [comment]
Hi, @StevenChorkley . This isn't possible currently, but i'll take a look if it can be implemented.

Adrian

**Comment by djrarky** [comment]
I'm trying to use it with Grafana, that's all I'm missing. That would be amazing!

Thank you!

**Comment by sofixa** [comment]
@StevenChorkley i've added host and VM uptime stats in version [0.8.4](https://github.com/Oxalide/vsphere-influxdb-go/releases/tag/v0.8.4), enjoy :)

Adrian

**Comment by djrarky** [comment]
Thank you. That's so kind. HNY!

**Comment by djrarky** [comment]
I'm so grateful with your help last time, but I really need to ask for it again :) 

I've been using the ESXi host uptime perfectly, but I can't manage to get out the VM's uptime. What I think should be the VM's uptime, is actually reporting the ESXi hosts. 

I'm sorry to ask - but please can you help me with this? 

Kind Regards,
Steven
![screenshot](https://user-images.githubusercontent.com/10834935/36613441-6b605718-18d1-11e8-82bb-3670ef6974a7.png)
