### ISSUE TITLE
vCenter query returns empty resultset

### ISSUE THREAD

**Issue by bartmeuris** [Oxalide/vsphere-influxdb-go#5]
I was very glad I found this tool, but I can't seem to get it working properly on my test setup.

I use vCenter 6.0.0 (Build 3634794). I tried debugging it a bit, but the VMWare API is a bit complex to fully dive into it in the time I currently have.

Most things seemed to work, but the following line always seemed to return an empty resultset, but no error:

    perfres, err := methods.QueryPerf(ctx, client.RoundTripper, &perfreq)

This is the log of the `-debug` output (which is not very helpful):

https://gist.github.com/bartmeuris/113cfde989287eb2be4cddc05f188abe

**Comment by sofixa** [comment]
Hi, 

Really sorry for the delay, i've been swamped.

Is this still going on?

I suppose it's a common ESXi issue, so if you have a single host and ff you go to its performance charts from the vCenter, and it says "no data available for this entity", then follow these tips (restart NTP and host management services) https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=5296658

Hope that helps,
Cheers,
Adrian

**Comment by patmagauran** [comment]
I have the same error on VMware ESXi 6.5.0 running standalone

**Comment by patmagauran** [comment]
After some debugging, the issue appears to be with the xml decoder in govmomi. The decoder gets sent xml and returns nil.

**Comment by ADeane6** [comment]
Any update on this I'm getting the same output

`2017/02/18 19:01:43 Querying vcenter
2017/02/18 19:01:43 Setting up query inventory of vcenter:  vcenter.home
2017/02/18 19:01:43 connecting to vcenter: vcenter.home
([]types.ManagedObjectReference) (len=15 cap=15) {
 (types.ManagedObjectReference) HostSystem:host-9,
 (types.ManagedObjectReference) VirtualMachine:vm-53,
 (types.ManagedObjectReference) VirtualMachine:vm-52,
 (types.ManagedObjectReference) VirtualMachine:vm-47,
 (types.ManagedObjectReference) VirtualMachine:vm-84,
 (types.ManagedObjectReference) VirtualMachine:vm-83,
 (types.ManagedObjectReference) VirtualMachine:vm-21,
 (types.ManagedObjectReference) VirtualMachine:vm-166,
 (types.ManagedObjectReference) VirtualMachine:vm-143,
 (types.ManagedObjectReference) VirtualMachine:vm-62,
 (types.ManagedObjectReference) VirtualMachine:vm-51,
 (types.ManagedObjectReference) VirtualMachine:vm-164,
 (types.ManagedObjectReference) VirtualMachine:vm-126,
 (types.ManagedObjectReference) VirtualMachine:vm-22,
 (types.ManagedObjectReference) VirtualMachine:vm-141
}
`

**Comment by sofixa** [comment]
@RotatingFans , did you get anywhere with the xml decoder? Probably one needs to use a specific version/update of some library for it to work?

**Comment by execcr** [comment]
I have the same issue: the db is empty, no point data show in grafana. I have the same output in console as Adeane6

**Comment by ridhoyp** [comment]
yea me too, theres just this picture show graph, 1kbps on network 

![image](https://cloud.githubusercontent.com/assets/28750276/26154481/d96b8258-3b39-11e7-866b-76b856983f50.png)

**Comment by sofixa** [comment]
Should be working now, check #17
