### ISSUE TITLE
Could not retrieve object names from vcenter

### ISSUE THREAD

**Issue by admin-pro** [Oxalide/vsphere-influxdb-go#51]
![image](https://user-images.githubusercontent.com/19953088/34167415-0941bedc-e4e2-11e7-90d6-6ea424ee6d4a.png)

**Comment by admin-pro** [comment]
Hello i have the following error,

You can see the screenshot bellow and i have forget the following line :+1: 
2017/12/19 17:29:01 Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 501 Not Implemented\r\nDate: Tue, 19 Dec 2017 16:29:01 GMT\r\nConnection: close\r\nContent-Type: text; charset=plain\r\nContent-Length: 0\r\n\r\n"; err=<nil>

can you help me please ? 

Thank you

**Comment by sofixa** [comment]
Hi, @admin-pro . 

Hmmm, that's a weird error :D 

What version of vCenter are you running? Is there anything specific, like is it running behind a reverse proxy, external PSC, etc. ?

Cheers,
Adrian

**Comment by artashus** [comment]
hi @admin-pro,

I had the same issue (v5.5), the reason were nested folders under rootfolder. Just commented 'if child.Type == "Datacenter"' and it fixed the issue for me. I do not know why guys are checking do the rootFolder.ChildEntity-es type =  'Datacenter',  entries might be also folders and later types.CreateContainerView{} has Recursive: true. Thus, will work (seems).

Have PR-ed,


Best,
/A

**Comment by sofixa** [comment]
@admin-pro could you give [v0.8.4.](https://github.com/Oxalide/vsphere-influxdb-go/releases/tag/v0.8.4) a try ? It includes @artashes-arabajyan 's fix and should fix your issue.

**Comment by artashus** [comment]
@sofixa just deployed this version... Thanks for -test...

**Comment by sofixa** [comment]
@artashes-arabajyan you're welcome!
