### ISSUE TITLE
ESXi 6.5

### ISSUE THREAD

**Issue by daximus522** [Oxalide/vsphere-influxdb-go#52]
I've been working on creating a dockerfile for this project and believe that I have a working model from the docker side (will share once I have fully validated).  However I can't seem to get it to pull any of my stats from ESXi.  I'm running the free version of ESXi 6.5.  When running with debug I see it iterate over my VMs but at the end it only posts and empty array to influx.  Do I need to adjust the collection levels (can I do that on the free ESXi?  can't seem to find it like was referenced in one of your links) to get ANY stats?

**Comment by DRDAVIDBANNER** [comment]
Hi

You need vcenter in order to gather the metrics, you can’t query a host directly 

Thanks

**Comment by sofixa** [comment]
Hi,

Actually you can get some(a pretty limited subset of the total metrics available with a vCenter), but you need a real licence, because IIRC free ESXi comes without APIs and the Performance Manager, which are used to query those metrics.

Adrian
