### ISSUE TITLE
influxdb ssl

### ISSUE THREAD

**Issue by doanerock** [Oxalide/vsphere-influxdb-go#57]
Is it possible to connect to influxdb using ssl certificates?

**Comment by sofixa** [comment]
Hello,

Yes, as long as the certificate is trusted by the system on which vsphere-influxdb-go will run.

Adrian

**Comment by doanerock** [comment]
I am asking because I don't see any documentation about how to set it up in the vsphere-influxdb.json or variables.  

For example this is how it is configured in the telegraf.conf file. 
   ssl_ca = "/etc/telegraf/ssl/server.pem"
   ssl_cert = "/etc/telegraf/ssl/server.pem"
   ssl_key = "/etc/telegraf/ssl/server.key"
