### ISSUE TITLE
Documentation of configuration file

### ISSUE THREAD

**Issue by gaetanquentin** [Oxalide/vsphere-influxdb-go#60]
Where is the documentation of configuration file?
I am  looking for information about:
 - interval : why must i configure interval since the script is launch every x time by a crontab?
 - how to integrate Some esxi?

my conf file contains for now a vcenter url with username and password and i want to add 5 esxi too : how to do it since the json section is named "vcenters"?

 "VCenters": 

- is there a way to have a more fine metrics (every 10 secondes)?
regards

**Comment by sofixa** [comment]
Hi,

The interval is referring to the VMware performance manager collection/rollup interval - basically the time period for which ESXi/vCenter will collect, aggregate and keep performance data(for more details, check out [the VMware docs](https://pubs.vmware.com/vsphere-50/index.jsp?topic=%2Fcom.vmware.wssdk.pg.doc_50%2FPG_Ch16_Performance.18.2.html) ). On vCenters, there are 4 default ones but you can add custom ones if you want.

You can add standalone ESXi hosts to the "vCenters" part, but you won't get all the metrics(most notably provisioning ones).

For 10 second metrics you have to setup a custom interval(not sure you can go that low though ) and query it.

**Comment by Devyno** [comment]
Not a golang user, but interested in the functionality of this code.
I ran this code and got errors connecting to any of my vcenters;
Not sure why , because the errors show that the info supplied in the config file is not being parced correctly.
Connecting to vcenter: xxxxvcwebvp02
Could not connect to vcenter: xxxxvcwebvp02
Error: Post https://<username>:<password>@xxxxvcwebvp02/sdk: invalid URL port "<password>"
Need help with why connnection to vcenter is failing..
Thanks

**Comment by sofixa** [comment]
@Deyno could you post (a sanitized version of ) your config file?

**Comment by Devyno** [comment]
Hell Adrian,

Below is my config file :

{
  "Domain": ".x1.local",
  "Interval": 60,
  "VCenters": [
    { "Username": "aalpha@x1.local", "Password": "passwd", "Hostname": "usmkevcenter05" }
  ],

  "InfluxDB": {
    "Prefix": "vsphere_",
    "Hostname": "http://10.5.x.x:8086",
    "Username": "capman",
    "Password": "passwddb",
    "Database": "vmwareperfmon"
  },

  "Metrics": [
    {
      "ObjectType": [ "VirtualMachine", "HostSystem" ],
      "Definition": [
        { "Metric": "cpu.usage.average", "Instances": "*" },
        { "Metric": "cpu.usage.maximum", "Instances": "*" },
        { "Metric": "cpu.usagemhz.average", "Instances": "*" },
        { "Metric": "cpu.usagemhz.maximum", "Instances": "*" },
        { "Metric": "cpu.wait.summation", "Instances": "*" },
        { "Metric": "cpu.system.summation", "Instances": "*" },
        { "Metric": "cpu.ready.summation", "Instances": "*" },
        { "Metric": "mem.usage.average", "Instances": "*" },
        { "Metric": "mem.usage.maximum", "Instances": "*" },
        { "Metric": "mem.consumed.average", "Instances": "*" },
        { "Metric": "mem.consumed.maximum", "Instances": "*" },
        { "Metric": "mem.active.average", "Instances": "*" },
        { "Metric": "mem.active.maximum", "Instances": "*" },
        { "Metric": "mem.vmmemctl.average", "Instances": "*" },
        { "Metric": "mem.vmmemctl.maximum", "Instances": "*" },
        { "Metric": "mem.totalCapacity.average", "Instances": "*" },
        { "Metric": "net.packetsRx.summation", "Instances": "*" },
        { "Metric": "net.packetsTx.summation", "Instances": "*" },
        { "Metric": "net.throughput.usage.average", "Instances": "*" },
        { "Metric": "net.received.average", "Instances": "*" },
        { "Metric": "net.transmitted.average", "Instances": "*" },
        { "Metric": "net.throughput.usage.nfs.average", "Instances": "*" },
        { "Metric": "datastore.numberReadAveraged.average", "Instances": "*" },
        { "Metric": "datastore.numberWriteAveraged.average", "Instances": "*" },
        { "Metric": "datastore.read.average", "Instances": "*" },
        { "Metric": "datastore.write.average", "Instances": "*" },
        { "Metric": "datastore.totalReadLatency.average", "Instances": "*" },
        { "Metric": "datastore.totalWriteLatency.average", "Instances": "*" },
        { "Metric": "mem.capacity.provisioned.average", "Instances": "*"},
        { "Metric": "cpu.corecount.provisioned.average", "Instances": "*" }
      ]
    },

    {
      "ObjectType": [ "VirtualMachine" ],
      "Definition": [
      { "Metric": "datastore.datastoreVMObservedLatency.latest", "Instances": "*" }
      ]
    },

    {




  *   Access to the influxdb is OK , but accessing the vcenter is erroring out with :

2018/05/15 12:11:05 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
2018/05/15 12:11:05 Successfully connected to Influx
2018/05/15 12:11:05 Connecting to vcenter: usmkevcenter05
2018/05/15 12:11:05 Could not connect to vcenter: usmkevcenter05
2018/05/15 12:11:05 Error: Post https://x1.local:passwd@usmkevcenter05/sdk: invalid URL port "passwd"
2018/05/15 12:11:05 Could not initialize connection to vcenter usmkevcenter05 Post https://x1.local:passwd@usmke usmkevcenter0505/sdk: invalid URL port " passwd "


For some reason it’s not parsing the config file correctly!!
Thanks for your help.

**Comment by Devyno** [comment]
I realized the # in my password was causing some of the problem, so I changed it.  Now I get this :

/usr/local/bin/vsphere-influxdb-go
2018/05/15 16:07:38 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
2018/05/15 16:07:38 Successfully connected to Influx
2018/05/15 16:07:38 Connecting to vcenter: 10.5.x.x
2018/05/15 16:07:38 Could not connect to vcenter: 10.5.x.x
2018/05/15 16:07:38 Error: Post https://10.5.195.185/sdk: Forbidden
2018/05/15 16:07:38 Could not initialize connection to vcenter 10.5.x.x Post https://10.5.x.x/sdk: Forbidden

Also tested the connection with :

$ curl --verbose -k -X POST  https://10.5.195.185/sdk
*   Trying 10.5.195.185...
* Connected to 10.5.x.x (10.5.x.x) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.0 / RSA_AES_128_CBC_SHA1
*              server certificate verification SKIPPED
*              server certificate status verification SKIPPED
*              common name: USMKE1VCSPP05.uhc1.local (does not match '10.5.195.185')
*              server certificate expiration date OK
*              server certificate activation date OK
*              certificate public key: RSA
*              certificate version: #3
*              subject: O=VMware\, Inc.,OU=VMware\, Inc.,CN=USMKE1VCSPP05.uhc1.local,EMAIL=support@vmware.com
*              start date: Mon, 28 Apr 2014 20:28:01 GMT
*              expire date: Thu, 25 Apr 2024 20:28:01 GMT
*              issuer: O=VMware\, Inc.,OU=VMware\, Inc.,CN=USMKE1VCSPP05.uhc1.local,EMAIL=support@vmware.com
*              compression: NULL
* ALPN, server did not agree to a protocol
> POST /sdk HTTP/1.1
> Host: 10.5.x.x
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Date: Tue, 15 May 2018 21:28:12 GMT
< Set-Cookie: vmware_soap_session="52355182-efb7-29a7-44dd-d007369cf96b"; Path=/; HttpOnly; Secure;
< Cache-Control: no-cache
< Connection: Keep-Alive
< Content-Type: text/xml; charset=utf-8
< Content-Length: 556
<
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soapenv:Body>
<soapenv:Fault>
  <faultcode>ClientFaultCode</faultcode>
  <faultstring>
Error returned by expat parser: no element found

while parsing HTTP request before method was determined
at line 1, column 0</faultstring>
</soapenv:Fault>
</soapenv:Body>
* Connection #0 to host 10.5.x.x left intact

Looks like I need to install an sdk kit , but do we have one in golang?




Below is my config file :

{
  "Domain": ".x1.local",
  "Interval": 60,
  "VCenters": [
    { "Username": "aalpha@x1.local", "Password": "passwd", "Hostname": "usmkevcenter05" }
  ],

  "InfluxDB": {
    "Prefix": "vsphere_",
    "Hostname": "http://10.5.x.x:8086",
    "Username": "capman",
    "Password": "passwddb",
    "Database": "vmwareperfmon"
  },

  "Metrics": [
    {
      "ObjectType": [ "VirtualMachine", "HostSystem" ],
      "Definition": [
        { "Metric": "cpu.usage.average", "Instances": "*" },
        { "Metric": "cpu.usage.maximum", "Instances": "*" },
        { "Metric": "cpu.usagemhz.average", "Instances": "*" },
        { "Metric": "cpu.usagemhz.maximum", "Instances": "*" },
        { "Metric": "cpu.wait.summation", "Instances": "*" },
        { "Metric": "cpu.system.summation", "Instances": "*" },
        { "Metric": "cpu.ready.summation", "Instances": "*" },
        { "Metric": "mem.usage.average", "Instances": "*" },
        { "Metric": "mem.usage.maximum", "Instances": "*" },
        { "Metric": "mem.consumed.average", "Instances": "*" },
        { "Metric": "mem.consumed.maximum", "Instances": "*" },
        { "Metric": "mem.active.average", "Instances": "*" },
        { "Metric": "mem.active.maximum", "Instances": "*" },
        { "Metric": "mem.vmmemctl.average", "Instances": "*" },
        { "Metric": "mem.vmmemctl.maximum", "Instances": "*" },
        { "Metric": "mem.totalCapacity.average", "Instances": "*" },
        { "Metric": "net.packetsRx.summation", "Instances": "*" },
        { "Metric": "net.packetsTx.summation", "Instances": "*" },
        { "Metric": "net.throughput.usage.average", "Instances": "*" },
        { "Metric": "net.received.average", "Instances": "*" },
        { "Metric": "net.transmitted.average", "Instances": "*" },
        { "Metric": "net.throughput.usage.nfs.average", "Instances": "*" },
        { "Metric": "datastore.numberReadAveraged.average", "Instances": "*" },
        { "Metric": "datastore.numberWriteAveraged.average", "Instances": "*" },
        { "Metric": "datastore.read.average", "Instances": "*" },
        { "Metric": "datastore.write.average", "Instances": "*" },
        { "Metric": "datastore.totalReadLatency.average", "Instances": "*" },
        { "Metric": "datastore.totalWriteLatency.average", "Instances": "*" },
        { "Metric": "mem.capacity.provisioned.average", "Instances": "*"},
        { "Metric": "cpu.corecount.provisioned.average", "Instances": "*" }
      ]
    },

    {
      "ObjectType": [ "VirtualMachine" ],
      "Definition": [
      { "Metric": "datastore.datastoreVMObservedLatency.latest", "Instances": "*" }
      ]
    },

    {




  *   Access to the influxdb is OK , but accessing the vcenter is erroring out with :

2018/05/15 12:11:05 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
2018/05/15 12:11:05 Successfully connected to Influx
2018/05/15 12:11:05 Connecting to vcenter: usmkevcenter05
2018/05/15 12:11:05 Could not connect to vcenter: usmkevcenter05
2018/05/15 12:11:05 Error: Post https://x1.local:passwd@usmkevcenter05/sdk: invalid URL port "passwd"
2018/05/15 12:11:05 Could not initialize connection to vcenter usmkevcenter05 Post https://x1.local:passwd@usmke usmkevcenter0505/sdk: invalid URL port " passwd "


For some reason it’s not parsing the config file correctly!!
Thanks for your help.




@deyno<https://github.com/deyno> could you post (a sanitized version of ) your config file?

**Comment by Devyno** [comment]
Hello could someone help with what configuration needs to be done on the vcenter for it to listen to requests at **https://<vcenter-ip>/sdk**  and allow access from the vsphere-influxdb-go  to read vcenter stats. ?
I am using vmware 6.0.

**Comment by Devyno** [comment]
Hello could someone help with what configuration needs to be done on the vcenter for it to listen to requests at https://vcenter-ip/sdk and allow access from the vsphere-influxdb-go to read vcenter stats. ?
I am using vmware 6.0.

**Comment by sofixa** [comment]
@Devyno so sorry for the very late reply.

Did you get it working ? If not and you're still interested, could you run it with -debug and -test to see how it parses the hostname and password? From what i've seen, govmomi doesn't like some special characters in passwords (iirc @ and ; cause some weird things).

Adrian
