### ISSUE TITLE
cpu.usage.average are not coming in percent unit

### ISSUE THREAD

**Issue by rohitkumargupta15** [Oxalide/vsphere-influxdb-go#65]
Hello 

cpu.usage.average metric are suppose to be in percent unit but in my case i am not getting data in percent unit .

> select cpu_usage_average from vsphere_hostsystem where "name"='abcesxi'
name: vsphere_hostsystem
time                cpu_usage_average
----                -----------------
1520242067000000000 729

Can someone hlep me how i can get the data in percent unit.
Thanks

**Comment by camskkz** [comment]
Hello,

This is because the values returned by vsphere are actually hundredth of percent (same for memory.usage.average). I found multiple docs online for the vsphere API and it was never written except here : https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/cpu.html

**Comment by sofixa** [comment]
Thanks for the help, @camskkz !
