### ISSUE TITLE
Uploading data to InfluxDB... Sometimes... Eventually...

### ISSUE THREAD

**Issue by audioeptesicus** [Oxalide/vsphere-influxdb-go#66]
This is a wonderful script. However, I'm encountering issues where it reports that data is uploading every 60 seconds, but Grafana and InfluxDB are not seeing it that way. I have my script looping in a simple bash file, that I then have created a service for, in lieu of using a cron job. I should note that this occurs when launching the go script manually, or executing it via the bash loop or crontab. Below, you can see that the script is executing about every 60 seconds and is sending data to InfluxDB, but if you look at the Grafana screenshot, only so much of it is actually being fed to the database. It's sporatic and isn't consistent. There might be some polls where it works a couple times every 60 seconds, or it might wait 5, 12, 20, minutes, or longer than an hour. Any ideas?

I should also note that I'm running Ubuntu 16.04 and have recently spun up two new servers (one for InfluxDB, and one for Grafana) specifically for isolating and troubleshooting the issue, without luck.

> eptesicus@7xGRAF:~$ sudo bash /usr/local/bin/vsphere-influxdb-exec.sh
> 2018/03/15 19:44:09 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
> 2018/03/15 19:44:09 Successfully connected to Influx
> 2018/03/15 19:44:09 Connecting to vcenter: 7xVCSA.7x.local
> 2018/03/15 19:44:09 Setting up query inventory of vcenter: 7xVCSA.7x.local
> 2018/03/15 19:44:09 Sent data to Influxdb from: 7xVCSA.7x.local
> 2018/03/15 19:45:09 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
> 2018/03/15 19:45:09 Successfully connected to Influx
> 2018/03/15 19:45:09 Connecting to vcenter: 7xVCSA.7x.local
> 2018/03/15 19:45:09 Setting up query inventory of vcenter: 7xVCSA.7x.local
> 2018/03/15 19:45:10 Sent data to Influxdb from: 7xVCSA.7x.local
> 2018/03/15 19:46:10 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
> 2018/03/15 19:46:10 Successfully connected to Influx
> 2018/03/15 19:46:10 Connecting to vcenter: 7xVCSA.7x.local
> 2018/03/15 19:46:10 Setting up query inventory of vcenter: 7xVCSA.7x.local
> 2018/03/15 19:46:10 Sent data to Influxdb from: 7xVCSA.7x.local
> 2018/03/15 19:47:10 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
> 2018/03/15 19:47:10 Successfully connected to Influx
> 2018/03/15 19:47:10 Connecting to vcenter: 7xVCSA.7x.local
> 2018/03/15 19:47:10 Setting up query inventory of vcenter: 7xVCSA.7x.local
> 2018/03/15 19:47:10 Sent data to Influxdb from: 7xVCSA.7x.local
> 2018/03/15 19:48:10 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
> 2018/03/15 19:48:10 Successfully connected to Influx
> 2018/03/15 19:48:10 Connecting to vcenter: 7xVCSA.7x.local
> 2018/03/15 19:48:11 Setting up query inventory of vcenter: 7xVCSA.7x.local
> 2018/03/15 19:48:11 Sent data to Influxdb from: 7xVCSA.7x.local
> 2018/03/15 19:49:11 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
> 2018/03/15 19:49:11 Successfully connected to Influx
> 2018/03/15 19:49:11 Connecting to vcenter: 7xVCSA.7x.local
> 2018/03/15 19:49:11 Setting up query inventory of vcenter: 7xVCSA.7x.local
> 2018/03/15 19:49:12 Sent data to Influxdb from: 7xVCSA.7x.local
> 2018/03/15 19:50:12 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
> 2018/03/15 19:50:12 Successfully connected to Influx
> 2018/03/15 19:50:12 Connecting to vcenter: 7xVCSA.7x.local
> 2018/03/15 19:50:12 Setting up query inventory of vcenter: 7xVCSA.7x.local
> 2018/03/15 19:50:12 Sent data to Influxdb from: 7xVCSA.7x.local
> 2018/03/15 19:51:12 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
> 2018/03/15 19:51:12 Successfully connected to Influx
> 2018/03/15 19:51:12 Connecting to vcenter: 7xVCSA.7x.local
> 2018/03/15 19:51:12 Setting up query inventory of vcenter: 7xVCSA.7x.local
> 2018/03/15 19:51:13 Sent data to Influxdb from: 7xVCSA.7x.local
> 2018/03/15 19:52:13 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
> 2018/03/15 19:52:13 Successfully connected to Influx
> 2018/03/15 19:52:13 Connecting to vcenter: 7xVCSA.7x.local
> 2018/03/15 19:52:13 Setting up query inventory of vcenter: 7xVCSA.7x.local
> 2018/03/15 19:52:13 Sent data to Influxdb from: 7xVCSA.7x.local
> 2018/03/15 19:53:13 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
> 2018/03/15 19:53:13 Successfully connected to Influx
> 2018/03/15 19:53:13 Connecting to vcenter: 7xVCSA.7x.local
> 2018/03/15 19:53:13 Setting up query inventory of vcenter: 7xVCSA.7x.local
> 2018/03/15 19:53:14 Sent data to Influxdb from: 7xVCSA.7x.local
> 2018/03/15 19:54:14 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
> 2018/03/15 19:54:14 Successfully connected to Influx
> 2018/03/15 19:54:14 Connecting to vcenter: 7xVCSA.7x.local
> 2018/03/15 19:54:14 Setting up query inventory of vcenter: 7xVCSA.7x.local
> 2018/03/15 19:54:14 Sent data to Influxdb from: 7xVCSA.7x.local
> 2018/03/15 19:55:14 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
> 2018/03/15 19:55:14 Successfully connected to Influx
> 2018/03/15 19:55:14 Connecting to vcenter: 7xVCSA.7x.local
> 2018/03/15 19:55:14 Setting up query inventory of vcenter: 7xVCSA.7x.local
> 2018/03/15 19:55:14 Sent data to Influxdb from: 7xVCSA.7x.local
> 2018/03/15 19:56:14 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
> 2018/03/15 19:56:14 Successfully connected to Influx
> 2018/03/15 19:56:14 Connecting to vcenter: 7xVCSA.7x.local
> 2018/03/15 19:56:15 Setting up query inventory of vcenter: 7xVCSA.7x.local
> 2018/03/15 19:56:15 Sent data to Influxdb from: 7xVCSA.7x.local
> 2018/03/15 19:57:15 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
> 2018/03/15 19:57:15 Successfully connected to Influx
> 2018/03/15 19:57:15 Connecting to vcenter: 7xVCSA.7x.local
> 2018/03/15 19:57:15 Setting up query inventory of vcenter: 7xVCSA.7x.local
> 2018/03/15 19:57:15 Sent data to Influxdb from: 7xVCSA.7x.local

![image](https://user-images.githubusercontent.com/25988545/37496804-085cfe90-288b-11e8-8f35-ff4010cdb3c1.png)

**Comment by sofixa** [comment]
Hi, sorry for the late reply, i've been swamped lately.

That's rather odd. Can you tell me some more about your setup, e.g. are you running InfluxDB behind a reverse proxy, relay, etc. ? Do you see entries corresponding to the times vsphere-influxdb-go is claiming to send the data in your InfluxDB logs (16.04, should be in journald, so journalctl -u influxdb.service) ? Have you tried running the script with -test and -debug flags, to see what exactly data does it collect ?


Cheers,
Adrian

**Comment by Devyno** [comment]
Could someone help with what needs to be done on the vcenter for this script to access the vcenter at https://vcenter-ip/sdk ?   
For any one that has gotten this script to work , what configuration is needed on the vcenter ?
I get this error : 

**2018/05/21 12:16:38 Error: Post https://10.5.4.1/sdk: Forbidden
2018/05/21 12:16:38 Could not initialize connection to vcenter 10.5.4.1 Post https://10.5.4.1/sdk:** Forbidden

Please help..

**Comment by jorioux** [comment]
@audioeptesicus To resolve this issue, you must set the minimum interval to 1 minute (the interval you've set in vsphere-influxdb-go.conf) :
![image](https://user-images.githubusercontent.com/876027/42779834-8eed740a-890f-11e8-93f8-b8ee6069b802.png)

And set "Null value" to null in the Display tab:
![image](https://user-images.githubusercontent.com/876027/42779908-c8fe3170-890f-11e8-99f5-d238c8f24b7c.png)

**Comment by kaushikrocks** [comment]
I am getting kind of similar error. Does anybody have the solution yet?

![error](https://user-images.githubusercontent.com/41431168/45347991-057f0880-b5cb-11e8-87cf-a21e120f2e18.PNG)
