### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by darox** [Oxalide/vsphere-influxdb-go#67]
I get a:
x509: certificate signed by unknown authority, although I use let's encrypt. What could cause that issue?
2018/03/24 19:51:14 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
2018/03/24 19:51:14 Could not connect to InfluxDB
2018/03/24 19:51:14 Get https://influx.damn.li/ping: x509: certificate signed by unknown authority

**Comment by sofixa** [comment]
Hi, 

That's odd, normally it should use your system's CAs. What's your OS? Does a curl work ? 

Cheers,
Adrian
