### ISSUE TITLE
Grafana integration

### ISSUE THREAD

**Issue by Croc2828** [Oxalide/vsphere-influxdb-go#73]
Hello all !

Sorry to disturb with my issue : I'm able to collect the vcenter information, the influxdb have record on it so I assume it's ok. In Grafana, I just imported the json dashboard, and configured it to use the influx database name. The problem here is that the graph remains empty. I think I'm missing something...

Can you please help ? :)

**Comment by Croc2828** [comment]
In the VARIABLES, I've check the query and execute it on the influx itself, and it return nothing :

InfluxDB shell version: 1.5.1
> use VMWARE
Using database VMWARE
> SHOW TAG VALUES FROM "virtualmachine" with key = "host"
> 
> 

I definitely miss something...

**Comment by MicKBfr** [comment]
Hello,

could you try
SHOW TAG VALUES FROM "virtualmachine" WITH KEY = "name" 
Or 
SHOW TAG VALUES FROM "vsphere_virtualmachine" WITH KEY = "name"

**Comment by sofixa** [comment]
@Croc2828 Can you post your config file (or the output from running with -debug), plus the (sanitized) output from:
```
SHOW DATABASES
SHOW MEASUREMENTS
```
(the second one might take some time if you have a lot of data on your InfluxDB)


There is probably something going on with database name / prefix.

Adrian

**Comment by Croc2828** [comment]
Dear all,

Thanks for the following up 👍 
@MicKBfr : The second request is working ! But the SHOW TAG VALUES FROM "vsphere_virtualmachine" WITH KEY = "name" where "host" =~ /^$vCenter$/ return anything.

@sofixa : 

[debug.txt](https://github.com/Oxalide/vsphere-influxdb-go/files/1888680/debug.txt)

> SHOW DATABASES
> name: databases
> name
> _internal
> VMWARE

> use VMWARE
> Using database VMWARE
> SHOW MEASUREMENTS
> name: measurements
> name
> vsphere_cpu
> vsphere_datastore
> vsphere_disk
> vsphere_hostsystem
> vsphere_net
> vsphere_resourcepool
> vsphere_virtualmachine


Thanks for the support !!!

**Comment by Croc2828** [comment]
Here is the settings of the dashboard too, I'm not quiet sure that the query for the vcenter is right.

<img width="723" alt="screen shot 2018-04-09 at 11 36 43" src="https://user-images.githubusercontent.com/34555767/38490783-525e8172-3bea-11e8-9fa5-e89f0f72686c.png">

**Comment by Croc2828** [comment]
I've just correct the $vcenter and $vmname variable now. The output are now ok, but I still don't see any data in Grafana.

**Comment by Croc2828** [comment]
Hello there, 

There is definitely something wrong with the prefix. I've just change the table value and now it's working on GRAFANA. I'm going to remove the prefix from the json config file and let you know.

<img width="754" alt="screen shot 2018-04-09 at 11 49 54" src="https://user-images.githubusercontent.com/34555767/38491822-5241c5c0-3bed-11e8-8794-f250f9312bc2.png">

**Comment by Croc2828** [comment]
Ok, I've remove the prefix from the json config file and now it's working ! 
Thanks for the support.
