### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by jackfrost82** [Oxalide/vsphere-influxdb-go#74]
Hi,
this is the output I get:

2018/04/19 12:07:36 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
2018/04/19 12:07:36 Successfully connected to Influx
2018/04/19 12:07:36 Connecting to vcenter: 172.25.244.12
2018/04/19 12:07:37 Setting up query inventory of vcenter: 172.25.244.12
2018/04/19 12:07:40 {"error":"Request Entity Too Large"}

[vsphere-influxdb-go.zip](https://github.com/Oxalide/vsphere-influxdb-go/files/1927695/vsphere-influxdb-go.zip)

I think the problem is the large number of vm on the same vcenter.
Is there any way to split the query?
Thanks

**Comment by ZHumphries** [comment]
I have the same issue with my 2 of my vcenters (around 3000 VM's each). The smaller VC's do not show the issue.

**Comment by ZHumphries** [comment]
This is acutally an INFLUXBD issue and can be resolved by setting 

max-body-size = 0

Specifies the maximum size (in bytes) of a client request body. When a client sends data that exceeds the configured maximum size, a 413 Request Entity Too Large HTTP response is returned. Setting this value to 0 disables the limit.

Environment variable: INFLUXDB_HTTP_MAX_BODY_SIZE

**Comment by sofixa** [comment]
Yep, we already had that issue in #54. @jackfrost82 can confirm if that fixes it for you?

**Comment by jackfrost82** [comment]
Fixed.
Thank you very much
