### ISSUE TITLE
realtime counters

### ISSUE THREAD

**Issue by ZHumphries** [Oxalide/vsphere-influxdb-go#76]
Is it possible to use gather real-time counters instead of the level 1 counters?

**Comment by sofixa** [comment]
Hi, @ZHumphries , sorry for the (very) late reply.

If you put 20 in the interval field in the configuration file (https://github.com/Oxalide/vsphere-influxdb-go/blob/master/vsphere-influxdb.json.sample#L3) it should collect realtime (20s) data.

Adrian
