### ISSUE TITLE
Error: Post https://10.5.4.1/sdk: Forbidden

### ISSUE THREAD

**Issue by Devyno** [Oxalide/vsphere-influxdb-go#78]
Need help with vcenter config to allow access , please help!

Connection to the influxdb ok but not vcenter. 
Vcenter connection gives error 

2018/05/21 12:16:38 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
2018/05/21 12:16:38 Successfully connected to Influx
2018/05/21 12:16:38 Connecting to vcenter: 10.5.4.1
2018/05/21 12:16:38 Could not connect to vcenter: 10.5.4.1
2018/05/21 12:16:38 Error: Post https://10.5.4.1/sdk: Forbidden
2018/05/21 12:16:38 Could not initialize connection to vcenter 10.5.4.1 Post https://10.5.4.1/sdk: Forbidden

**Comment by sofixa** [comment]
Hi, that probably means the user you're using to login to vCenter either can't login(wrong user/password) or doesn't have sufficient privileges ( read-only is sufficient).

Adrian

**Comment by Devyno** [comment]
Hello Adrain, thanks for responding.

But I do have access to the vcenter web gui. Do I need a different access for the sdk?





Hi, that probably means the user you're using to login to vCenter either can't login(wrong user/password) or doesn't have sufficient privileges ( read-only is sufficient).

Adrian

**Comment by sofixa** [comment]
Yep, you can have a user with acces to the web GUI(for instance a VM Power user role) but not to the performance counters. What's your user's roles?

**Comment by Devyno** [comment]
Attached are some screen shots but didn’t find any roles for Power users. Looks like that needs to be created:

[cid:image001.png@01D3F0F4.BE6C2040][cid:image002.png@01D3F0F4.BE6C2040][cid:image003.png@01D3F0F4.BE6C2040]

Or you could direct me how to check.
Thanks


Yep, you can have a user with acces to the web GUI(for instance a VM Power user role) but not to the performance counters. What's your user's roles?

**Comment by sofixa** [comment]
Hi @Devyno , sorry for the very late reply! 

Did you get it working? If not, you can check if you can connect to the vCenter with govc or PowerCLI.

Adrian

**Comment by kaushikrocks** [comment]
Does anyone get this working?
I still face the same issue.
![error](https://user-images.githubusercontent.com/41431168/45356616-51d54300-b5e1-11e8-8d1f-c40e9f5c8996.PNG)
