### ISSUE TITLE
Difference b/w vCenter and Influx for cpu_ready with default Interval parameter

### ISSUE THREAD

**Issue by cgb** [Oxalide/vsphere-influxdb-go#8]
Hey, thanks for publishing this code, it's working really well... except, I found that for cpu_ready_summations, it is inaccurate.  Comparing data logged in Influx, with the vSphere client, I found the values in Influx to be 3-4 times larger.  I think that is because of the way VMware's API works for start/end time:

https://www.vmware.com/support/developer/vc-sdk/visdk400pubs/ReferenceGuide/vim.PerformanceManager.QuerySpec.html
"If the range between startTime and endTime crosses multiple sample interval periods, the result contains data from the longest interval in the period."

By setting the Interval config parameter to 20, I found the numbers much more similar, although not exactly equal to vSphere client.  Do you know anything more about this and whether what I'm doing is right/wrong? :)

**Comment by sofixa** [comment]
@cgb do you encounter this only on cpu_ready_summation or on all metrics?

**Comment by cblomart** [comment]
vsphere-influxdb-go forces realtime collection (intervalID=20). Per default the collection inverval (60s) doesn't cross any other intervall as the next one is 300 secs.
What would happen is that the collected metrics are summed. As there is 3 times 20 seconds in one minut, the reported values would be 3 times larger.

**Comment by sofixa** [comment]
Yeah, @cblomart , with intervalID=60 it should work better.
