### ISSUE TITLE
Sporadic ServerFaultCode error

### ISSUE THREAD

**Issue by jorioux** [Oxalide/vsphere-influxdb-go#83]
I've configured the go file to execute every minute using cron. It works fine, but I get sporadic ServerFaultCode errors causing holes in the Grafana graphs:

![image](https://user-images.githubusercontent.com/876027/42780146-7b1eb08c-8910-11e8-8ef1-b0d27c2face6.png)

The error from the go file output is this:

```
2018/07/16 15:41:01 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
2018/07/16 15:41:01 Successfully connected to Influx
2018/07/16 15:41:01 Connecting to vcenter: vcenter.staplesams.com
2018/07/16 15:41:01 Setting up query inventory of vcenter: vcenter.staplesams.com
2018/07/16 15:41:03 Sent data to Influxdb from: vcenter.staplesams.com
2018/07/16 15:41:58 Could not request perfs from vcenter: vcenter.staplesams.com
2018/07/16 15:41:58 Error: ServerFaultCode: A general system error occurred: Operation was canceled
```

What could cause this?

**Comment by sofixa** [comment]
Hi,

Can you check on the VMware side, in the details of the task you should have some more information on what's going on?

Adrian

**Comment by jorioux** [comment]
I don't get those errors anymore, it fixed itself.
