### ISSUE TITLE
XML Error when polling.

### ISSUE THREAD

**Issue by zerolimit5** [Oxalide/vsphere-influxdb-go#84]
Im getting the following error when i the cronjob runs.  Has anyone seen this error before.  I do not see where the element max is set if there is a setting for it.  Any help is greatly appreciated.

2018/07/25 12:43:22 Could not request perfs from vcenter: vcenter.local.local.com
2018/07/25 12:43:22 Error:  ServerFaultCode: XML document element count exceeds configured maximum 500000

while parsing serialized DataObject of type vim.PerformanceManager.MetricId
at line 2, column 11543514

while parsing property "metricId" of static type ArrayOfPerfMetricId

while parsing serialized DataObject of type vim.PerformanceManager.QuerySpec
at line 2, column 11534500

while parsing call information for method QueryPerf
at line 2, column 66

while parsing SOAP body
at line 2, column 60

while parsing SOAP envelope
at line 2, column 0

while parsing HTTP request for method queryStats
on object of type vim.PerformanceManager
at line 1, column 0

**Comment by sofixa** [comment]
Hi,

What version of vCenter are you using? Can you show me a (sanitized) version of your configuration file?

Adrian
