### ISSUE TITLE
stopped working after password vsphere password changed

### ISSUE THREAD

**Issue by v4vamsee** [Oxalide/vsphere-influxdb-go#85]
After changing the vcenter account password, I no longer see the data being written to the influxdb.

However, when I run following:

./vsphere-influxdb-go 

I see:

2018/08/01 15:53:11 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
2018/08/01 15:53:11 Successfully connected to Influx
2018/08/01 15:53:11 Connecting to vcenter: xxxxxx.xxx.xxx.cm
2018/08/01 15:53:11 Setting up query inventory of vcenter: xxxxxx.xxx.xxx.cm
2018/08/01 15:53:37 Sent data to Influxdb from: xxxxxx.xxx.xxx.cm

However, there is no data displayed in grafana connected to my influxdb database.

This has happened to me twice in the past, most of the times it majically started working again.
This time it totally stopped working. My graphs are empty in grafana.

**Question:**

If the vcenter password is changed after installed, will it break metric gathering?
Is there any special configuration I need to enable in influxdb?

**Comment by sofixa** [comment]
Hi,

Normally, a password change changes absolutely nothing. Could you run with -debug and -test flags, like this:

```
./vsphere-influxdb-go -debug -test
```
To see what data does it collect?

Adrian
