### ISSUE TITLE
{"error":"Request Entity Too Large"}

### ISSUE THREAD

**Issue by EricWang8230** [Oxalide/vsphere-influxdb-go#86]
Hi,
I run  ./vsphere-influxdb-go
2018/08/04 15:31:41 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
2018/08/04 15:31:41 Successfully connected to Influx
2018/08/04 15:31:41 Connecting to vcenter: my vCenter IP
2018/08/04 15:31:41 Setting up query inventory of vcenter: my vCenter IP
2018/08/04 15:31:48 {"error":"Request Entity Too Large"}

Does the message indicate that my host disk space is not enough? 
Or is my vCenter metrics too large?

* My vCenter scale is 29 ESXi and about 2000 VMs.

Thanks.

**Comment by sofixa** [comment]
Hi, 

It means the data collected is too much.
You should check on the receiving side ( InfluxDB, any proxies or relays you have before that), the max request size. In InfluxDB it's a setting in the configuration file, and 0 sets it to unlimited.

Cheers,
Adrian

**Comment by EricWang8230** [comment]
Hi Adrian,

I edit the Influxdb config 'max-body-size = 0' and the problem is solved.
Thank you.

Eric

**Comment by tryfan** [comment]
For anyone else having this issue:  In my environment, changing the max size for influx was going to be a pain.  A good solution is to run a telegraf instance and set the input http_listener (influxdb_listener with telegraf > 1.9.0).  

Point the config towards that endpoint, and it will send your metrics on to the influxdb instance.
