### ISSUE TITLE
authorization failed

### ISSUE THREAD

**Issue by trockenasche** [Oxalide/vsphere-influxdb-go#87]
I'm getting "authorization failed" message after query inventory
```
2018/08/09 16:22:07 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
2018/08/09 16:22:07 Successfully connected to Influx
2018/08/09 16:22:07 Connecting to vcenter: vcenter20.domain.int
2018/08/09 16:22:08 Setting up query inventory of vcenter: vcenter20.domain.int
2018/08/09 16:22:08 {"error":"authorization failed"}
```
The monitoring user has a read only role but I even change the role of this user to administrator role, but this didn't helped either.

**Comment by sofixa** [comment]
Hi, 

Are you sure you have the right user and password? Are there special characters in the password (i think mostly ", \, \, stuff like that)? 

Adrian

**Comment by trockenasche** [comment]
Hi Adrian,

I'm sure that I have the right user and password.
This is what I get when it's the wrong password:
```
2018/08/09 19:21:20 Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
2018/08/09 19:21:20 Successfully connected to Influx
2018/08/09 19:21:20 Connecting to vcenter: vcenter20.domain.int
2018/08/09 19:21:25 Could not connect to vcenter: vcenter20.domain.int
2018/08/09 19:21:25 Error: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
2018/08/09 19:21:25 Could not initialize connection to vcenter vcenter20.domain.int ServerFaultCode: Cannot complete login due to an incorrect user name or password.
```

Thanks,
Murdoc

**Comment by trockenasche** [comment]
Found it, it was my fault.
It was a wrong password for InfluxDB. But because of the message `Successfully connected to Influx` I never thought about this.
