### ISSUE TITLE
config file error (windows)

### ISSUE THREAD

**Issue by BrandonAUS** [Oxalide/vsphere-influxdb-go#88]
When running the exe from a windows server it is trying to put /etc/ before the file path of the config file.

e.g.

/etc/c:\Users\USERNAME\documents\

therefore it fails to find the file and doesn't run. 

Is there something I need to change to get this to work?

**Comment by sofixa** [comment]
Hi,

You can use the -config flag to specify where the configuration file should be.

Adrian

**Comment by BrandonAUS** [comment]
All sorted, thanks.
