### ISSUE TITLE
Parse error invalid URL escape %ga

### ISSUE THREAD

**Issue by tdekoning93** [Oxalide/vsphere-influxdb-go#9]
How do I solve this error?
@vcenter.despite.nl/sdk: invalid URL escape "%ga"

Running vCenter 6.5 latest update. It does manage to login.

**Comment by sofixa** [comment]
Huh, weird, i have one 6.5b vCenter and it works fine. 

It seems it's a go lib error - https://golang.org/src/net/url/url.go .

Could you post the relevant part of your JSON(vCenter url), obfucsated, of course? 
What happens when you go manually to the page in question(https://fqdn/sdk) ?

**Comment by tdekoning93** [comment]
@sofixa When I go manually to the SDK page, it says the page cannot be found. According to VMware that is expected behaviour? https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1003218

I can go to https://fqdn/sdk/vimService.wsdl. That returns an XML file.

```
{
        "Domain": ".nl",
        "Interval": 60,
        "VCenters": [
                { "Username": "user", "Password": "password", "Hostname": "vcenter.despite.nl" }

        ],
```

Above is the configuration part for vCenter.

**Comment by sofixa** [comment]
@tdekoning93 Did you manage to sort this out? 

If not, could you provide some more info, like the full output of running with -debug, versions of everything, etc. 

Cheers,
Adrian
