### ISSUE TITLE
Issues compiling - ./vsphere-influxdb.go:478:13: device.Backing undefined (type types.BaseVirtualDevice has no field or method Backing)

### ISSUE THREAD

**Issue by PLColuccio** [Oxalide/vsphere-influxdb-go#92]
So when I run the go get command, I receive:
`go/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:447:67: syntax error: unexpected = at end of statement`

I edit the line 447 to:
`hostSummary[host.Self]["name"] = host.Summary.Config.Name`

Then when I run go compile I receive:
`./vsphere-influxdb.go:478:13: device.Backing undefined (type types.BaseVirtualDevice has no field or method Backing)`

`./vsphere-influxdb.go:482:37: device.diskObjectId undefined (type types.BaseVirtualDevice has no field or method diskObjectId)`

`./vsphere-influxdb.go:482:60: device.Backing undefined (type types.BaseVirtualDevice has no field or method Backing)`

Version:
`paul@E0I999AP01:~/go/src/github.com/oxalide/vsphere-influxdb-go$ go version
go version go1.9.7 linux/amd64
`

I am new to go, so any help appreciated.

**Comment by MicKBfr** [comment]
Hi,

i have made mistake on line 447. i'm new to go too. But there is another bug on line 482. you can comment line from 476 to 484 or take previous build.

good luck

**Comment by sofixa** [comment]
Hi, @phreak2599 , @MicKBfr sorry that i kept you waiting, i've been swamped lately.

I've fixed the issues (i started working on new features on the master branch and didn't have the time to finish them, so it was broken for some time). Master is now fixed and a new working version [0.8.5](https://github.com/Oxalide/vsphere-influxdb-go/releases) is out.

Adrian
