### ISSUE TITLE
Going inside clusters

### ISSUE THREAD

**Issue by accodepull** [Oxalide/vsphere-influxdb-go#94]
Suddenly it stopped working (no data received) and using the -debug the last line I see is "Going inside clusters".
Is there any further debugging that can be done to identify where the issue is (vcenter/influxdb)? 
(Date/Time on VM running the script and vsphere hosts is correct)

Thanks

**Comment by sofixa** [comment]
Hi, @contiandrea .

Can you send me a sanitized version of the output from running with -test and -debug?

Adrian

**Comment by accodepull** [comment]
Hi Adrian,  am doing further checks to confirm that the cluster performance data is available within vCenter in the first place. I will get back with an update as soon as I can.
In meantime please let me know if there is any option that can give more information about the stage of Going into clusters.

Thanks
